### ISSUE TITLE
Unable to load lwjgl library

### ISSUE THREAD

**Issue by maxanzh** [LWJGL/lwjgl3#112]
OS Windows 8, x64
lwjgl-3.0.0b-20151108.202554-63.jar
library from https://oss.sonatype.org/content/repositories/snapshots/ 

```java
java.lang.ExceptionInInitializerError
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:56) ~[lwjgl-3.0.0b-20151108.202554-63.jar:?]
	at org.lwjgl.system.libffi.Closure.<clinit>(Closure.java:39) ~[lwjgl-3.0.0b-20151108.202554-63.jar:?]
	at com.rsgames.engine.graphics.test.innerRenderer.TestInnerRenderer.play(TestInnerRenderer.java:105) ~[classes/:?]
	at com.rsgames.engine.graphics.test.innerRenderer.TestInnerRenderer.main(TestInnerRenderer.java:44) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:?]
Caused by: java.lang.NullPointerException
	at org.lwjgl.system.Library.loadLibrary(Library.java:155) ~[lwjgl-3.0.0b-20151108.202554-63.jar:?]
	at org.lwjgl.system.Library.loadSystem(Library.java:69) ~[lwjgl-3.0.0b-20151108.202554-63.jar:?]
	at org.lwjgl.system.Library.<clinit>(Library.java:27) ~[lwjgl-3.0.0b-20151108.202554-63.jar:?]
	... 9 more

```

**Comment by httpdigest** [comment]
I get this error, too.
Only happens when explicitly setting `Configuration.LIBRARY_PATH` to a non-null string.
After looking into it, it happens, because the static initializer which runs this code happens before actually initializing/instantiating `Library.LOADER_SYSTEM`, which is used there.

**Comment by ShchAlexander** [comment]
Thanks)
