### ISSUE TITLE
Library loading error

### ISSUE THREAD

**Issue by ShchAlexander** [LWJGL/lwjgl3#113]
OS: Win 8 x64
LIB: lwjgl-3.0.0b-20151109.115337-64

When I trying to run demos error occurs: 
```java
java.lang.ExceptionInInitializerError
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:56)
	at org.lwjgl.system.libffi.Closure.<clinit>(Closure.java:39)
	at org.lwjgl.demo.opengl.UniformArrayDemo.init(UniformArrayDemo.java:61)
	at org.lwjgl.demo.opengl.UniformArrayDemo.run(UniformArrayDemo.java:272)
	at org.lwjgl.demo.opengl.UniformArrayDemo.main(UniformArrayDemo.java:289)
Caused by: java.lang.NullPointerException
	at org.lwjgl.system.Library.loadLibrary(Library.java:155)
	at org.lwjgl.system.Library.loadSystem(Library.java:69)
	at org.lwjgl.system.Library.<clinit>(Library.java:27)
	... 5 more
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.system.MemoryUtil
	at org.lwjgl.system.Pointer.<clinit>(Pointer.java:24)
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:592)
	at org.lwjgl.demo.opengl.UniformArrayDemo.run(UniformArrayDemo.java:284)
	at org.lwjgl.demo.opengl.UniformArrayDemo.main(UniformArrayDemo.java:289)
```

It happens because *LOADER_SYSTEM* is not initialized in Library class when it used for loading *lwjgl* library  *`Library.loadSystem(Library.java:69)`*

**Comment by httpdigest** [comment]
Huh??? This is exactly the same as #112 , and you even commented on #112 with "Thanks)"...

**Comment by ShchAlexander** [comment]
I assumed that the problem is solved. But.... It happens again... Maybe I'm doing something wrong?)

**Comment by httpdigest** [comment]
Judging from the line numbers you are seemingly still using an old version.
I confirm that the bug in #112 is resolved with the latest build #3.0.0b build 58, 09 Nov 15 11:53.

**Comment by httpdigest** [comment]
And it also does work with the latest lwjgl3 Maven library version 3.0.0b-SNAPSHOT from oss.sonatype.org.

**Comment by ShchAlexander** [comment]
I'm sorry. All is works.

**Comment by sriharshachilakapati** [comment]
In case if the problem is not solved, please re-open your previous issue instead of creating new issue which is exactly a copy of your old issue.
