### ISSUE TITLE
bug with natives load

### ISSUE THREAD

**Issue by infernalbuild** [LWJGL/lwjgl3#123]
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.lwjgl.system.MemoryUtil.memPointerSize()I
	at org.lwjgl.system.MemoryUtil.memPointerSize(Native Method)
	at org.lwjgl.Pointer.<clinit>(Pointer.java:22)
	at org.lwjgl.PointerBuffer.<init>(PointerBuffer.java:24)
	at org.lwjgl.PointerBuffer.allocateDirect(PointerBuffer.java:281)
	at org.lwjgl.BufferUtils.createPointerBuffer(BufferUtils.java:190)
	at org.lwjgl.system.libffi.Closure.<clinit>(Closure.java:45)
	at org.infernalbuild.hypergrapheditor.Main.main(Main.java:38)

Main.java:38 refer to the first call of lwjgl (glfwSetErrorCallback)

**Comment by Spasi** [comment]
Make sure `-Djava.library.path` is set correctly.

**Comment by sriharshachilakapati** [comment]
Shouldn't the first call of LWJGL should be `glfwInit()` ?

**Comment by infernalbuild** [comment]
with glfwInit() i get

Exception in thread "main" java.lang.UnsatisfiedLinkError: org.lwjgl.glfw.GLFW.nglfwInit()I
	at org.lwjgl.glfw.GLFW.nglfwInit(Native Method)
	at org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:429)

and -Djava.library.path is set correctly

**Comment by infernalbuild** [comment]
but i have an another project where it work perfectly and the sources are the same !!!?????

**Comment by sriharshachilakapati** [comment]
This is not a bug, it's just that the location of natives is referring to a non existing path I think. What I do is to keep a folder called as natives alongside the `src` dir, and add this before calling `glfwInit()` function.

```java
Configuration.LIBRARY_PATH.set("natives");
```

And it should work automatically.

**Comment by infernalbuild** [comment]
when i try with Configuration.LIBRARY_PATH.set("natives"); i get the same error

before i used 

System.setProperty("org.lwjgl.librarypath", new File("native").getAbsolutePath()); 

but the result was the same

and File("native") is the right one

**Comment by Spasi** [comment]
Please reopen this issue if you still have trouble with the latest nightly build.
