### ISSUE TITLE
JEMalloc trying to load 32 bit binary on 64-bit windows

### ISSUE THREAD

**Issue by sriharshachilakapati** [LWJGL/lwjgl3#142]
I'm having an issue where LWJGL is trying to load 32-bit binary `jemalloc32.dll` on 64-bit Windows 10. This is the debug log from LWJGL.

~~~
[INFO 02/05/2016 10:53:18 PM] Initializing LWJGL library. Extracting natives.
[INFO 02/05/2016 10:53:18 PM] LWJGL version 3.0.0 build 21 is initialised
[INFO 02/05/2016 10:53:18 PM] [LWJGL] Version: 3.0.0 build 21
[INFO 02/05/2016 10:53:18 PM] [LWJGL] 	 OS: Windows 8.1 v6.3
[INFO 02/05/2016 10:53:18 PM] [LWJGL] 	JRE: 1.8.0_51 amd64
[INFO 02/05/2016 10:53:18 PM] [LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v25.51-b03 by Oracle Corporation
[INFO 02/05/2016 10:53:18 PM] [LWJGL] Loaded library from org.lwjgl.librarypath: lwjgl
[INFO 02/05/2016 10:53:18 PM] [LWJGL] MemoryUtil accessor: MemoryAccessorUnsafe
[WARNING 02/05/2016 10:53:18 PM] Caused by: java.lang.RuntimeException: Failed to load library: jemalloc32.dll (error code = 126)
[WARNING 02/05/2016 10:53:18 PM] [LWJGL] [MemoryAllocator] Failed to load the jemalloc library.
[INFO 02/05/2016 10:53:18 PM] java.lang.ExceptionInInitializerError
[INFO 02/05/2016 10:53:18 PM] at java.lang.Class.forName0(Native Method)
[INFO 02/05/2016 10:53:18 PM] at java.lang.Class.forName(Class.java:264)
[INFO 02/05/2016 10:53:18 PM] at org.lwjgl.system.MemoryManage.getInstance(MemoryManage.java:36)
[INFO 02/05/2016 10:53:18 PM] at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:66)
[INFO 02/05/2016 10:53:18 PM] at org.lwjgl.system.Library.<clinit>(Library.java:63)
[INFO 02/05/2016 10:53:18 PM] at org.lwjgl.system.MemoryAccess.<clinit>(MemoryAccess.java:22)
[INFO 02/05/2016 10:53:18 PM] at org.lwjgl.system.Pointer.<clinit>(Pointer.java:24)
[INFO 02/05/2016 10:53:18 PM] at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:594)
~~~

I think this is by default, but by overriding the property via `Configuration` class, I'm able to make it load the 64-bit binary. Like this.

~~~java
Configuration.LIBRARY_NAME_JEMALLOC.set("jemalloc");
~~~

I'm using LWJGL3 update 21.

**Comment by Spasi** [comment]
Thanks!
