### ISSUE TITLE
Error loading libraries (Linux)

### ISSUE THREAD

**Issue by germangb** [LWJGL/lwjgl3#156]
I'm getting this exception when trying to run the latest nightly release:

> Exception in thread "main" java.lang.ExceptionInInitializerError
	at Test.main(Test.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
**Caused by: java.lang.RuntimeException: Failed to dynamically load library: /home/germangb/IdeaProjects/Tpa/Desktop/native/libglfw.so(error = /: cannot read file data: Is a directory)**
	at org.lwjgl.system.linux.LinuxLibrary.<init>(LinuxLibrary.java:23)
	at org.lwjgl.system.APIUtil.apiCreateLibrary(APIUtil.java:63)
	at org.lwjgl.system.Library$2.load(Library.java:33)
	at org.lwjgl.system.Library$2.load(Library.java:30)
	at org.lwjgl.system.Library.loadLibrary(Library.java:201)
	at org.lwjgl.system.Library.loadNative(Library.java:138)
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:652)
	... 6 more

I tried different releases and have had no trouble with tose

**Comment by Spasi** [comment]
This was just fixed, see #155. Build 55 will be up in a few minutes.

**Comment by germangb** [comment]
okay! Sorry for the duplicate
