### ISSUE TITLE
java.lang.IllegalArgumentException: Malformed API version string

### ISSUE THREAD

**Issue by joelross** [LWJGL/lwjgl3#161]
Using the current version on sonatype (Linux build), I get this exception when calling `GLES.createCapabilities()`:

```
[error] Caused by: java.lang.ExceptionInInitializerError
[error] 	at org.lwjgl.opengles.GLES$1.getFunctionAddress(GLES.java:111)
[error] 	at org.lwjgl.opengles.GLES.createCapabilities(GLES.java:193)
[error] 	[...]
[error] Caused by: java.lang.IllegalArgumentException: Malformed API version string [EGL_EXT_client_extensions]
[error] 	at org.lwjgl.system.APIUtil.apiParseVersion(APIUtil.java:127)
[error] 	at org.lwjgl.egl.EGL.createClientCapabilities(EGL.java:166)
[error] 	at org.lwjgl.egl.EGL.create(EGL.java:128)
[error] 	at org.lwjgl.egl.EGL.create(EGL.java:110)
[error] 	at org.lwjgl.egl.EGL.create(EGL.java:67)
[error] 	at org.lwjgl.egl.EGL.<clinit>(EGL.java:46)
[error] 	[...]
```

Been a little while since I last used LWJGL, but I suspect this has something to do with [this recent change](https://github.com/LWJGL/lwjgl3/commit/22e8f34dbcbcbf526ef02fc1db11e063271ae4b8#diff-b81b2ebe5e91866187c816910f4e0b9fR159).

**Comment by Spasi** [comment]
Thanks!
