### ISSUE TITLE
Exception calling GLX extension methods

### ISSUE THREAD

**Issue by Tobi29** [LWJGL/lwjgl3#192]
Calling any GLX functions (e.g. GLX13.glXChooseFBConfig) that require the capabilities instance throws the following exception:
```
java.lang.IndexOutOfBoundsException: 1
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at org.lwjgl.opengl.GL.createCapabilitiesGLX(GL.java:562)
	at org.lwjgl.opengl.GL.initCapabilitiesGLX(GL.java:280)
	at org.lwjgl.opengl.GL.getCapabilitiesGLXClient(GL.java:260)
```
Looking at 143459daf1038537282260f6e07726df7637aa2c this might be a typo?
Manually calling these functions using JNI.call works fine.

**Comment by Spasi** [comment]
Thanks!
