### ISSUE TITLE
Incompatible system libjemalloc.so loaded on Arch Linux

### ISSUE THREAD

**Issue by Bobo1239** [LWJGL/lwjgl3#196]
```
16:47:38.287 [main] INFO LWJGL - 	libjemalloc.so not found in org.lwjgl.librarypath=/tmp/lwjglbobo1239/c055ad3b
16:47:38.288 [main] INFO LWJGL - 	Loaded from java.library.path: /usr/lib64/libjemalloc.so
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.system.MemoryManage$JEmallocAllocator.config(MemoryManage.java:100)
	at org.lwjgl.system.MemoryUtil$LazyInit.<clinit>(MemoryUtil.java:81)
	at org.lwjgl.system.MemoryUtil.nmemAlloc(MemoryUtil.java:162)
	at org.lwjgl.system.MemoryUtil.memAlloc(MemoryUtil.java:180)
	at org.lwjgl.system.MemoryUtil.memUTF8(MemoryUtil.java:1530)
	at org.lwjgl.system.APIUtil.apiArrayi(APIUtil.java:430)
	at org.lwjgl.opengl.GL20.glShaderSource(GL20.java:425)
	at bms.opengl.Shader.<init>(Shader.java:36)
	at bms.font.Font.initialize(Font.java:86)
	at bms.font.FontManager.initialize(FontManager.java:17)
	at bms.Bms.initialize(Bms.java:82)
	at bms.Bms.main(Bms.java:36)
Caused by: java.lang.IllegalStateException: This function is not available.
	at org.lwjgl.system.Checks.checkFunctionAddress(Checks.java:89)
	at org.lwjgl.system.APIUtil.apiGetFunctionAddress(APIUtil.java:121)
	at org.lwjgl.system.jemalloc.JEmalloc$Functions.<clinit>(JEmalloc.java:46)
	... 12 more
```

LWJGL tries to use the system `libjemalloc.so` (in `/usr/lib64/`) in the path but it doesn't work. When I rename the file and force LWJGL to unpack and use the ones from the `natives-linux` package, there's no problem.
(System [jemalloc](https://www.archlinux.org/packages/extra/x86_64/jemalloc/) version: 4.2.0 )

**Comment by Spasi** [comment]
Could you please post the full output when running with `-Dorg.lwjgl.util.Debug=true`? It looks like the `ShaderLibraryLoader` is being used, but it fails to extract `libjemalloc.so` in the temp folder.

**Comment by Bobo1239** [comment]
```
17:09:22.408 [main] INFO LWJGL - Version: 3.0.0 build 90
17:09:22.409 [main] INFO LWJGL -     OS: Linux v4.6.2-1-ARCH
17:09:22.409 [main] INFO LWJGL -    JRE: 1.8.0_92 amd64
17:09:22.409 [main] INFO LWJGL -    JVM: OpenJDK 64-Bit Server VM v25.92-b14 by Oracle Corporation
17:09:22.409 [main] INFO LWJGL - Loading library (system): lwjgl
17:09:22.431 [main] INFO LWJGL -    liblwjgl.so not found in java.library.path=.::/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
17:09:22.431 [main] INFO LWJGL -    Using SharedLibraryLoader...
17:09:22.432 [main] INFO LWJGL -    Extracting: file:/home/bobo1239/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-platform/3.0.0/f622d9e6aea3ab20e8d57ea02083310f067209d0/lwjgl-platform-3.0.0-natives-linux.jar!/liblwjgl.so
17:09:22.462 [main] INFO LWJGL -    Loaded from org.lwjgl.librarypath: /tmp/lwjglbobo1239/c055ad3b/liblwjgl.so
17:09:22.490 [main] INFO LWJGL - ThreadLocalUtil state: UnsafeState
17:09:22.497 [main] INFO LWJGL - MemoryUtil accessor: MemoryAccessorUnsafe
17:09:22.508 [main] INFO LWJGL - Loading library: glfw
17:09:22.511 [main] INFO LWJGL -    Loaded from org.lwjgl.librarypath: /tmp/lwjglbobo1239/c055ad3b/libglfw.so
17:09:22.875 [main] INFO LWJGL - Loading library: libGL.so.1
17:09:22.879 [main] INFO LWJGL -    libGL.so.1 not found in org.lwjgl.librarypath=/tmp/lwjglbobo1239/c055ad3b
17:09:22.880 [main] INFO LWJGL -    Loaded from java.library.path: /usr/lib64/libGL.so.1
17:09:23.237 [main] INFO LWJGL - [GL] Using KHR_debug for error logging.
17:09:23.248 [main] INFO LWJGL - Loading library: openal
17:09:23.248 [main] INFO LWJGL -    libopenal.so not found in org.lwjgl.librarypath=/tmp/lwjglbobo1239/c055ad3b
17:09:23.249 [main] INFO LWJGL -    Loaded from java.library.path: /usr/lib64/libopenal.so
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
17:09:23.534 [main] INFO LWJGL - Loading library: jemalloc
17:09:23.534 [main] INFO LWJGL -    libjemalloc.so not found in org.lwjgl.librarypath=/tmp/lwjglbobo1239/c055ad3b
17:09:23.535 [main] INFO LWJGL -    Loaded from java.library.path: /usr/lib64/libjemalloc.so
Exception in thread "main" java.lang.ExceptionInInitializerError
    at org.lwjgl.system.MemoryManage$JEmallocAllocator.config(MemoryManage.java:100)
    at org.lwjgl.system.MemoryUtil$LazyInit.<clinit>(MemoryUtil.java:81)
    at org.lwjgl.system.MemoryUtil.nmemAlloc(MemoryUtil.java:162)
    at org.lwjgl.system.MemoryUtil.memAlloc(MemoryUtil.java:180)
    at org.lwjgl.system.MemoryUtil.memUTF8(MemoryUtil.java:1530)
    at org.lwjgl.system.APIUtil.apiArrayi(APIUtil.java:430)
    at org.lwjgl.opengl.GL20.glShaderSource(GL20.java:425)
    at bms.opengl.Shader.<init>(Shader.java:36)
    at bms.font.Font.initialize(Font.java:86)
    at bms.font.FontManager.initialize(FontManager.java:17)
    at bms.Bms.initialize(Bms.java:82)
    at bms.Bms.main(Bms.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.IllegalStateException: This function is not available.
    at org.lwjgl.system.Checks.checkFunctionAddress(Checks.java:89)
    at org.lwjgl.system.APIUtil.apiGetFunctionAddress(APIUtil.java:121)
    at org.lwjgl.system.jemalloc.JEmalloc$Functions.<clinit>(JEmalloc.java:46)
    ... 17 more
```
The temp directory contains the extracted `libglfw.so` and `liblwjgl.so`. If I rename my system `libjemalloc.so`, `libjemalloc.so` also gets extracted to the temp directory and everything works. Starting the application after `libjemalloc.so` is present in the temp directory, there is no problem as the temp directory apprantly has a higher precedence in the load path.

**Comment by Spasi** [comment]
Thanks, that was helpful. The problem seems to be that `java.library.path` includes `/usr/lib64/` by default. Both libjemalloc.so and libopenal.so are loaded from there.

Could you please run the same with `-Djava.library.path=.`? I'm pretty sure it'll fail again, but I'd like to see the output.

**Comment by Bobo1239** [comment]
```
17:53:14.444 [main] INFO bms.Bms - Hello LWJGL 3.0.0 build 90!
17:53:14.466 [main] INFO LWJGL - Version: 3.0.0 build 90
17:53:14.466 [main] INFO LWJGL - 	 OS: Linux v4.6.2-1-ARCH
17:53:14.467 [main] INFO LWJGL - 	JRE: 1.8.0_92 amd64
17:53:14.467 [main] INFO LWJGL - 	JVM: OpenJDK 64-Bit Server VM v25.92-b14 by Oracle Corporation
17:53:14.467 [main] INFO LWJGL - Loading library (system): lwjgl
17:53:14.482 [main] INFO LWJGL - 	liblwjgl.so not found in java.library.path=.
17:53:14.483 [main] INFO LWJGL - 	Using SharedLibraryLoader...
17:53:14.489 [main] INFO LWJGL - 	Extracting: file:/home/bobo1239/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-platform/3.0.0/f622d9e6aea3ab20e8d57ea02083310f067209d0/lwjgl-platform-3.0.0-natives-linux.jar!/liblwjgl.so
17:53:14.520 [main] INFO LWJGL - 	Loaded from org.lwjgl.librarypath: /tmp/lwjglbobo1239/c055ad3b/liblwjgl.so
17:53:14.542 [main] INFO LWJGL - ThreadLocalUtil state: UnsafeState
17:53:14.548 [main] INFO LWJGL - MemoryUtil accessor: MemoryAccessorUnsafe
17:53:14.561 [main] INFO LWJGL - Loading library: glfw
17:53:14.565 [main] INFO LWJGL - 	Loaded from org.lwjgl.librarypath: /tmp/lwjglbobo1239/c055ad3b/libglfw.so
17:53:14.907 [main] INFO LWJGL - Loading library: libGL.so.1
17:53:14.908 [main] INFO LWJGL - 	libGL.so.1 not found in org.lwjgl.librarypath=/tmp/lwjglbobo1239/c055ad3b
17:53:14.910 [main] INFO LWJGL - 	libGL.so.1 not found in java.library.path=.
17:53:14.911 [main] INFO LWJGL - 	Loaded from system paths
17:53:15.254 [main] INFO LWJGL - [GL] Using KHR_debug for error logging.
17:53:15.267 [main] INFO LWJGL - Loading library: openal
17:53:15.267 [main] INFO LWJGL - 	libopenal.so not found in org.lwjgl.librarypath=/tmp/lwjglbobo1239/c055ad3b
17:53:15.267 [main] INFO LWJGL - 	libopenal.so not found in java.library.path=.
17:53:15.268 [main] INFO LWJGL - 	Loaded from system paths
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
17:53:15.612 [main] INFO LWJGL - Loading library: jemalloc
17:53:15.612 [main] INFO LWJGL - 	libjemalloc.so not found in org.lwjgl.librarypath=/tmp/lwjglbobo1239/c055ad3b
17:53:15.613 [main] INFO LWJGL - 	libjemalloc.so not found in java.library.path=.
17:53:15.613 [main] INFO LWJGL - 	Loaded from system paths
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.system.MemoryManage$JEmallocAllocator.config(MemoryManage.java:100)
	at org.lwjgl.system.MemoryUtil$LazyInit.<clinit>(MemoryUtil.java:81)
	at org.lwjgl.system.MemoryUtil.nmemAlloc(MemoryUtil.java:162)
	at org.lwjgl.system.MemoryUtil.memAlloc(MemoryUtil.java:180)
	at org.lwjgl.system.MemoryUtil.memUTF8(MemoryUtil.java:1530)
	at org.lwjgl.system.APIUtil.apiArrayi(APIUtil.java:430)
	at org.lwjgl.opengl.GL20.glShaderSource(GL20.java:425)
	at bms.opengl.Shader.<init>(Shader.java:36)
	at bms.font.Font.initialize(Font.java:86)
	at bms.font.FontManager.initialize(FontManager.java:17)
	at bms.Bms.initialize(Bms.java:82)
	at bms.Bms.main(Bms.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.IllegalStateException: This function is not available.
	at org.lwjgl.system.Checks.checkFunctionAddress(Checks.java:89)
	at org.lwjgl.system.APIUtil.apiGetFunctionAddress(APIUtil.java:121)
	at org.lwjgl.system.jemalloc.JEmalloc$Functions.<clinit>(JEmalloc.java:46)
	... 17 more
```

**Comment by Spasi** [comment]
The fix is in 3.0.1 build 2. Let me know if it works for you please.

**Comment by Bobo1239** [comment]
Perfect; Thank you!

**Comment by pierr3** [comment]
I'm having a similar error with the latest build on Windows:

`[LWJGL] Version: 3.0.1 build 2      
[LWJGL]          OS: Windows 10 v10.0
[LWJGL]         JRE: 1.8.0_73 amd64 
[LWJGL]         JVM: Java HotSpot(TM) 64-Bit Server VM v25.73-b02 by Oracle Corporation
[LWJGL] Loading library (system): lwjgl
[LWJGL]         Using SharedLibraryLoader...[LWJGL]     Extracting: file:/C:/Users/Pierre/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-platform/3.0.1-SNAPSHOT/7b0656b2cd70e44f
29e0205acf12af777bcbe424/lwjgl-platform-3.0.1-SNAPSHOT-natives-windows.jar!/lwjgl.dll
found                               
[LWJGL]         Loaded from org.lwjgl.librarypath: C:\Users\Pierre\AppData\Local\Temp\lwjglPierre\e31e074f\lwjgl.dll
[LWJGL] ThreadLocalUtil state: UnsafeState
[LWJGL] MemoryUtil accessor: MemoryAccessorUnsafe
[LWJGL] Loading library: jemalloc   
[LWJGL]         Loaded from org.lwjgl.librarypath: C:\Users\Pierre\AppData\Local\Temp\lwjglPierre\e31e074f\jemalloc.dll
[LWJGL] MemoryUtil allocator: JEmallocAllocator
[LWJGL] Loading library: glfw       
[LWJGL]         Loaded from org.lwjgl.librarypath: C:\Users\Pierre\AppData\Local\Temp\lwjglPierre\e31e074f\glfw.dll
[LWJGL] Loading library: opengl32   
[LWJGL]         opengl32.dll not found in org.lwjgl.librarypath=C:\Users\Pierre\AppData\Local\Temp\lwjglPierre\e31e074f
[LWJGL]         Using SharedLibraryLoader...failed
java.lang.RuntimeException:     Failed to extract opengl32 library
        at org.lwjgl.system.SharedLibraryLoader.load(SharedLibraryLoader.java:65)
        at org.lwjgl.system.Library.loadNative(Library.java:152)
        at org.lwjgl.system.Library.loadNative(Library.java:225)
        at org.lwjgl.opengl.GL.create(GL.java:102)
        at org.lwjgl.opengl.GL.<clinit>(GL.java:86)
        at net.vatsim.vsky.radar.RadarWindowRenderer.initializeContext(RadarWindowRenderer.java:80)
        at net.vatsim.vsky.radar.RadarWindowRenderer.run(RadarWindowRenderer.java:73)
Caused by: java.lang.RuntimeException: Failed to locate resource: opengl32.dll
        at org.lwjgl.system.SharedLibraryLoader.extractFile(SharedLibraryLoader.java:80)
        at org.lwjgl.system.SharedLibraryLoader.load(SharedLibraryLoader.java:63)
        ... 6 more                  
[LWJGL]         Loaded from java.library.path: C:\WINDOWS\system32\opengl32.dll
[LWJGL] [GL] GL_ARB_shader_subroutine was reported as available but an entry point is missing.
`

The folder "C:\Users\Pierre\AppData\Local\Temp\lwjglPierre\e31e074f" contains only glfw.dll, jemalloc.dll and lwjgl.dll

**Comment by Spasi** [comment]
You can ignore the exception related to opengl32.dll (your application works, right?). The next build should fix it.

**Comment by pierr3** [comment]
It does work, thanks!
