### ISSUE TITLE
org.lwjgl.system.macosx.CoreFoundation.nCFBundleGetBundleWithIdentifier(J)J

### ISSUE THREAD

**Issue by JuKu** [LWJGL/lwjgl3#227]
Hi,

We have an new problem:
```
0 [main] DEBUG root  - java.library.path set to /Users/<User>/Desktop/client-0.0.2-SNAPSHOT_Mac (4)/natives.
1 [main] DEBUG root  - java.library.path: /Users/<User>/Desktop/client-0.0.2-SNAPSHOT_Mac (4)/natives
3 [main] INFO root  - use cache configuration file cfg/cache.cfg .
30 [main] INFO root  - Platform issue: {USER} isnt supported in configuration files.
147 [main] DEBUG root  - BasicGameStateEngine constructor executed successful.
147 [main] DEBUG root  - parse configuration.
152 [main] DEBUG root  - create new thread for default memory cache cleanup.
[LWJGL] [WARNING] Mismatch detected between the Java and native LWJGL libraries.
  Launch the JVM with -Dorg.lwjgl.util.Debug=true for more information.
OpenALC10: true
OpenALC11: true
caps.ALC_EXT_EFX = true
Default device: OpenAL Soft
ALC_FREQUENCY: 44100Hz
ALC_REFRESH: 43Hz
ALC_SYNC: false
ALC_MONO_SOURCES: 255
ALC_STEREO_SOURCES: 1
368 [main] DEBUG root  - Game constructor executed successfully.
407 [main] ERROR root  - GLFW Error: 65538, description: 4987086587.
407 [main] DEBUG root  - initialize renderer.
409 [main] INFO root  - create window.
413 [main] DEBUG root  - create GLFWContext in Thread main.
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.lwjgl.system.macosx.CoreFoundation.nCFBundleGetBundleWithIdentifier(J)J
  at org.lwjgl.system.macosx.CoreFoundation.nCFBundleGetBundleWithIdentifier(Native Method)
  at org.lwjgl.system.macosx.CoreFoundation.CFBundleGetBundleWithIdentifier(CoreFoundation.java:195)
  at org.lwjgl.system.macosx.MacOSXLibraryBundle.getWithIdentifier(MacOSXLibraryBundle.java:29)
  at org.lwjgl.system.macosx.MacOSXLibrary.getWithIdentifier(MacOSXLibrary.java:20)
  at org.lwjgl.glfw.EventLoop$OffScreen.<clinit😠EventLoop.java:33)
  at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1633)
  at com.pentaquin.core.context.GLFWContext.createWindow(GLFWContext.java:613)
  at com.pentaquin.core.context.OpenGLGLFWContext.<init😠OpenGLGLFWContext.java:21)
  at com.pentaquin.core.application.GLFWWindow.<init😠GLFWWindow.java:24)
  at com.pentaquin.core.application.PentaCoreEngine.initRenderer(PentaCoreEngine.java:95)
  at com.pentaquin.core.application.BasicGameStateEngine.init(BasicGameStateEngine.java:162)
  at com.pentaquin.client.game.GameMain.main(GameMain.java:64)
```

![photo_2016-09-02_14-22-47](https://cloud.githubusercontent.com/assets/1138046/18205654/6ac7d828-7123-11e6-9424-676a70a0c2ee.png)

createWindow method:
```java
protected void createWindow(final HashMap<Integer,Integer> windowHints, boolean defaultHints)
	{
		if (defaultHints)
		{
			GLFW.glfwDefaultWindowHints();
		}

		for (HashMap.Entry<Integer,Integer> entry : windowHints.entrySet())
		{
			GLFW.glfwWindowHint(entry.getKey(), entry.getValue());
		}

		//create the window
		if(!fullscreen)
		{
			window = GLFW.glfwCreateWindow(800, 600, "Pentaquin", 0, 0);
		}
		else
		{
			//save the current monitor
			monitor = GLFW.glfwGetPrimaryMonitor();
			GLFWVidMode vidmode = GLFW.glfwGetVideoMode(monitor);
			//create the window on the primary monitor
			window = GLFW.glfwCreateWindow(vidmode.width(), vidmode.height(), "Pentaquin", GLFW.glfwGetPrimaryMonitor(), 0);
		}

		keyCallback = GLFWKeyCallback.create((long window, int key, int scancode, int action, int mods) ->
		{
			invoke(window, key, scancode, action, mods);
		});

		cursorCallback = GLFWCursorPosCallback.create((long window, double xpos, double ypos) ->
		{
			invoke(window, xpos, ypos);
		});

		closeCallback = GLFWWindowCloseCallback.create((long window) -> {
			Logger.getRootLogger().debug("close window");

			//call callback
			invoke(window);
		});

		focusCallback = GLFWWindowFocusCallback.create((long window, boolean focused) ->
		{
			invoke(window, focused);
		});

		//set the com.pentaquin.core.input callbacks

		//set keyboard callbacks
		GLFW.glfwSetKeyCallback(window, keyCallback);

		GLFW.glfwSetCursorPosCallback(window, cursorCallback);

		//set the window callbacks
		GLFW.glfwSetWindowCloseCallback(window, closeCallback);
		GLFW.glfwSetWindowFocusCallback(window, focusCallback);
	}
```

Its the same method as discussed here, but another bug:
#221 

What does this exception mean?
This exception is only thrown with Mac OSX, it works on windows and linux.

**Comment by JuKu** [comment]
Its the same method as discussed here, but another bug:
#221

**Comment by sriharshachilakapati** [comment]
It might be that you are having the non-modular version natives with the new 3.0.1 SNAPSHOT. This line explains that error:

> [LWJGL] [WARNING] Mismatch detected between the Java and native LWJGL libraries.
  Launch the JVM with -Dorg.lwjgl.util.Debug=true for more information.

And as far as I know, LWJGL uses the platform's library loading instead of Java's `System.loadLibrary` method for the natives. Maybe that is the issue you are having.

**Comment by JuKu** [comment]
@sriharshachilakapati Thanks for your answer!
But why does it works with windows and linux?

**Comment by sriharshachilakapati** [comment]
It maybe that Windows and Linux OSes already have the natives in the temp directory. The natives are only extracted when the libraries aren't available in the temp directory. Clean the temp directory and try again on Windows or Linux, maybe that will reveal something.
