### ISSUE TITLE
Failed to instantiate memory allocator: org.lwjgl.system.jemalloc.JEmallocAllocator

### ISSUE THREAD

**Issue by JuKu** [LWJGL/lwjgl3#243]
Hi,

We get this exception:
```
java.lang.ClassNotFoundException: org.lwjgl.system.jemalloc.JEmallocAllocator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.lwjgl.system.MemoryManage.getInstance(MemoryManage.java:36)
	at org.lwjgl.system.MemoryUtil$LazyInit.<clinit>(MemoryUtil.java:76)
	at org.lwjgl.system.MemoryUtil.getAllocator(MemoryUtil.java:138)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:67)
	at com.pentaquin.core.context.GLFWContextMaster.init(GLFWContextMaster.java:41)
	at com.pentaquin.core.application.BasicGameStateEngine.createAndInitContext(BasicGameStateEngine.java:186)
	at com.pentaquin.core.application.BasicGameStateEngine.init(BasicGameStateEngine.java:157)
	at com.pentaquin.client.game.GameMain.main(GameMain.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
[LWJGL] Failed to instantiate memory allocator: org.lwjgl.system.jemalloc.JEmallocAllocator
[LWJGL] MemoryUtil allocator: StdlibAllocator
```

How can we fix this?

**Comment by Spasi** [comment]
Either add the jemalloc module to your project or call `Configuration.MEMORY_ALLOCATOR.set("system")` before using LWJGL (equivalently start the JVM with `-Dorg.lwjgl.system.allocator=system`).

**Comment by sriharshachilakapati** [comment]
That means you have not included JEmalloc bindings in your project. Either do that, or you can set the allocator to Stdlib.

~~~java
Configuration.MEMORY_ALLOCATOR.set("system");
~~~

This should fix it.

**Comment by JuKu** [comment]
Thanks to your answers!
I have fixed this issue with adding dependencie for JEmallocAllocator.

But now, i get an new exception:
```
[LWJGL] Loading library: jemalloc
[LWJGL] 	Extracting: file:/D:/Users/<User>/.gradle/caches/modules-2/files-2.1/org.lwjgl/lwjgl-jemalloc/3.0.1-SNAPSHOT/1390bc6f4282cf33f4f31608ce89ac64fd581edc/lwjgl-jemalloc-3.0.1-SNAPSHOT-natives-windows.jar!/jemalloc.dll
[LWJGL] 	jemalloc.dll not found in java.library.path=D:\Users\<User>\IdeaProjects\pentaquin-client\build/natives/windows/
[LWJGL] 	jemalloc.dll not found in system paths
[LWJGL] Failed to load a library. Possible solutions:
	a) Set -Djava.library.path or -Dorg.lwjgl.librarypath to the directory that contains the shared libraries.
	b) Add the JAR(s) containing the shared libraries to the classpath.
java.lang.UnsatisfiedLinkError: Failed to locate library: jemalloc.dll
	at org.lwjgl.system.Library.loadNative(Library.java:202)
	at org.lwjgl.system.jemalloc.JEmalloc.<clinit>(JEmalloc.java:37)
	at org.lwjgl.system.jemalloc.JEmallocAllocator.<clinit>(JEmallocAllocator.java:17)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.lwjgl.system.MemoryManage.getInstance(MemoryManage.java:36)
	at org.lwjgl.system.MemoryUtil$LazyInit.<clinit>(MemoryUtil.java:76)
	at org.lwjgl.system.MemoryUtil.getAllocator(MemoryUtil.java:138)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:67)
	at com.pentaquin.core.context.GLFWContextMaster.init(GLFWContextMaster.java:41)
	at com.pentaquin.core.application.BasicGameStateEngine.createAndInitContext(BasicGameStateEngine.java:186)
	at com.pentaquin.core.application.BasicGameStateEngine.init(BasicGameStateEngine.java:157)
	at com.pentaquin.client.game.GameMain.main(GameMain.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
[LWJGL] Failed to instantiate memory allocator: org.lwjgl.system.jemalloc.JEmallocAllocator
```

**Comment by sriharshachilakapati** [comment]
You also need the JEmalloc natives. Add this runtime configuration.

~~~groovy
runtime "org.lwjgl:lwjgl-jemalloc:3.0.1-SNAPSHOT:natives-windows"
~~~

**Comment by JuKu** [comment]
Thanks! :D
We have resolved this issue now. :D
