### ISSUE TITLE
Failed to instantiate memory allocator

### ISSUE THREAD

**Issue by kellerkindt** [LWJGL/lwjgl3#268]
Cant get a Vulkan application running, maybe I am doing something wrong?

## With 3.0.1 + 3.1.2
Line causing the error:
```java
    private static final ByteBuffer ENGINE_NAME     = MemoryUtil.memASCII("vulkanTest");
```

```
[LWJGL] Version: 3.1.2 build 4
[LWJGL] 	 OS: Linux v4.8.0-32-generic
[LWJGL] 	JRE: 1.8.0_111 amd64
[LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v25.111-b14 by Oracle Corporation
[LWJGL] Loading library (system): lwjgl
[LWJGL] 	Extracting: file:/share/home/michael/.m2/repository/org/lwjgl/lwjgl-platform/3.0.1-SNAPSHOT/lwjgl-platform-3.0.1-20160621.215043-5-natives-linux.jar!/liblwjgl.so
[LWJGL] 	Loaded from org.lwjgl.librarypath: /tmp/lwjglmichael/3.1.2-build-4/liblwjgl.so
[LWJGL] [WARNING] Mismatch detected between the Java and native libraries.
java.lang.UnsatisfiedLinkError: org.lwjgl.system.MemoryAccessJNI.malloc()J
	at org.lwjgl.system.MemoryAccessJNI.malloc(Native Method)
	at org.lwjgl.system.MemoryAccessJNI.<clinit>(MemoryAccessJNI.java:29)
	at org.lwjgl.system.Pointer.<clinit>(Pointer.java:22)
	at org.lwjgl.system.MemoryAccess$MemoryAccessorUnsafe.getAddressOffset(MemoryAccess.java:162)
	at org.lwjgl.system.MemoryAccess$MemoryAccessorUnsafe.<clinit>(MemoryAccess.java:153)
	at org.lwjgl.system.MemoryAccess.getInstance(MemoryAccess.java:30)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:58)
	at com.kellerkindt.vulkan.VulkanApplication.<clinit>(VulkanApplication.java:26)
	at com.kellerkindt.vulkan2d.Main.main(Main.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
[LWJGL] [MemoryAccessor] Unsupported JVM detected, this will likely result in low performance. Please inform LWJGL developers.
[LWJGL] MemoryUtil accessor: MemoryAccessorJNI
[LWJGL] Warning: Failed to instantiate memory allocator: org.lwjgl.system.jemalloc.JEmallocAllocator. Using the system default.
[LWJGL] MemoryUtil allocator: StdlibAllocator
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.lwjgl.system.libc.LibCStdlib.nmalloc(J)J
	at org.lwjgl.system.libc.LibCStdlib.nmalloc(Native Method)
	at org.lwjgl.system.MemoryManage$StdlibAllocator.malloc(MemoryManage.java:71)
	at org.lwjgl.system.MemoryUtil.nmemAlloc(MemoryUtil.java:145)
	at org.lwjgl.system.MemoryUtil.memAlloc(MemoryUtil.java:163)
	at org.lwjgl.system.MemoryUtil.memASCII(MemoryUtil.java:1182)
	at org.lwjgl.system.MemoryUtil.memASCII(MemoryUtil.java:1167)
	at com.kellerkindt.vulkan.VulkanApplication.<clinit>(VulkanApplication.java:26)
	at com.kellerkindt.vulkan2d.Main.main(Main.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.kellerkindt</groupId>
    <artifactId>vulkan2d</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <lwjgl.version>3.1.2-SNAPSHOT</lwjgl.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.googlecode.mavennatives</groupId>
                <artifactId>maven-nativedependencies-plugin</artifactId>
                <version>0.0.5</version>
                <executions>
                    <execution>
                        <id>unpacknatives</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl</artifactId>
            <version>${lwjgl.version}</version>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-glfw</artifactId>
            <version>${lwjgl.version}</version>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-vulkan</artifactId>
            <version>${lwjgl.version}</version>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-platform</artifactId>
            <version>3.0.1-SNAPSHOT</version>
            <classifier>natives-linux</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-platform</artifactId>
            <version>3.0.1-SNAPSHOT</version>
            <classifier>natives-windows</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-platform</artifactId>
            <version>3.0.1-SNAPSHOT</version>
            <classifier>natives-osx</classifier>
        </dependency>
    </dependencies>


    <repositories>
        <repository>
            <id>lwjgl-nightly</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>

        <repository>
            <id>mavenNatives</id>
            <name>Maven Natives Repository</name>
            <url>http://mavennatives.googlecode.com/svn/repo</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>


</project>
```

## With 3.0.1:
Line causing the error:
```java
        this.glfwErrorCallback  = GLFWErrorCallback.createPrint().set();
```
```
[LWJGL] Version: 3.0.1 build 35
[LWJGL] 	 OS: Linux v4.8.0-32-generic
[LWJGL] 	JRE: 1.8.0_111 amd64
[LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v25.111-b14 by Oracle Corporation
[LWJGL] Loading library (system): lwjgl
[LWJGL] 	Found at: /tmp/lwjglmichael/3.0.1-build-35/liblwjgl.so
[LWJGL] 	Loaded from org.lwjgl.librarypath: /tmp/lwjglmichael/3.0.1-build-35/liblwjgl.so
[LWJGL] [WARNING] Mismatch detected between the Java and native libraries.
[LWJGL] MemoryUtil accessor: MemoryAccessorUnsafe
java.lang.ClassNotFoundException: org.lwjgl.system.jemalloc.JEmallocAllocator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.lwjgl.system.MemoryManage.getInstance(MemoryManage.java:36)
	at org.lwjgl.system.MemoryUtil$LazyInit.<clinit>(MemoryUtil.java:76)
	at org.lwjgl.system.MemoryUtil.nmemAlloc(MemoryUtil.java:145)
	at org.lwjgl.system.MemoryUtil.memAlloc(MemoryUtil.java:163)
	at org.lwjgl.system.MemoryUtil.memASCII(MemoryUtil.java:1321)
	at org.lwjgl.system.MemoryUtil.memASCII(MemoryUtil.java:1306)
	at com.kellerkindt.vulkan.VulkanApplication.<clinit>(VulkanApplication.java:26)
	at com.kellerkindt.vulkan2d.Main.main(Main.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
[LWJGL] Failed to instantiate memory allocator: org.lwjgl.system.jemalloc.JEmallocAllocator
[LWJGL] MemoryUtil allocator: StdlibAllocator
[LWJGL] ThreadLocalUtil state: UnsafeState
[LWJGL] Loading library: glfw
[LWJGL] 	Found at: /tmp/lwjglmichael/3.0.1-build-35/libglfw.so
[LWJGL] 	Loaded from org.lwjgl.librarypath: /tmp/lwjglmichael/3.0.1-build-35/libglfw.so
[LWJGL] [WARNING] Mismatch detected between the Java and native libraries.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.nglfwSetErrorCallback(GLFW.java:853)
	at org.lwjgl.glfw.GLFW.glfwSetErrorCallback(GLFW.java:882)
	at org.lwjgl.glfw.GLFWErrorCallback.set(GLFWErrorCallback.java:111)
	at com.kellerkindt.vulkan.VulkanApplication.<init>(VulkanApplication.java:69)
	at com.kellerkindt.vulkan2d.Main.main(Main.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IllegalStateException: This function is not available.
	at org.lwjgl.system.Checks.checkFunctionAddress(Checks.java:94)
	at org.lwjgl.system.APIUtil.apiGetFunctionAddress(APIUtil.java:120)
	at org.lwjgl.glfw.GLFW$Functions.<clinit>(GLFW.java:620)
	... 10 more
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.kellerkindt</groupId>
    <artifactId>vulkan2d</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <lwjgl.version>3.0.1-SNAPSHOT</lwjgl.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.googlecode.mavennatives</groupId>
                <artifactId>maven-nativedependencies-plugin</artifactId>
                <version>0.0.5</version>
                <executions>
                    <execution>
                        <id>unpacknatives</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl</artifactId>
            <version>${lwjgl.version}</version>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-glfw</artifactId>
            <version>${lwjgl.version}</version>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-vulkan</artifactId>
            <version>${lwjgl.version}</version>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-platform</artifactId>
            <version>${lwjgl.version}</version>
            <classifier>natives-linux</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-platform</artifactId>
            <version>${lwjgl.version}</version>
            <classifier>natives-windows</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-platform</artifactId>
            <version>${lwjgl.version}</version>
            <classifier>natives-osx</classifier>
        </dependency>
    </dependencies>


    <repositories>
        <repository>
            <id>lwjgl-nightly</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>

        <repository>
            <id>mavenNatives</id>
            <name>Maven Natives Repository</name>
            <url>http://mavennatives.googlecode.com/svn/repo</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>


</project>
```

**Comment by httpdigest** [comment]
In the first pom.xml you are not using the same version for the natives than what you use for the Java class jar files. You also see `[LWJGL] [WARNING] Mismatch detected between the Java and native libraries.` in the log. This means that LWJGL3 is picking up natives from another version than the Java classes it loads from the jar files.
Also: With LWJGL3 you don't have to unpack the natives or do anything to the natives anymore. You can just add the jar files containing the natives to the classpath and it will work.

**Comment by kellerkindt** [comment]
Forced maven to redownload lwjgl dependencies (deleted in ~/m2/), but still having the same issue:

```java
    private static final ByteBuffer ENGINE_NAME     = MemoryUtil.memASCII("kellerVulkan");
```

```
[LWJGL] Version: 3.0.1 build 35
[LWJGL] 	 OS: Linux v4.8.0-32-generic
[LWJGL] 	JRE: 1.8.0_111 amd64
[LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v25.111-b14 by Oracle Corporation
[LWJGL] Loading library (system): lwjgl
[LWJGL] 	Found at: /tmp/lwjglmichael/3.0.1-build-35/liblwjgl.so
[LWJGL] 	Loaded from org.lwjgl.librarypath: /tmp/lwjglmichael/3.0.1-build-35/liblwjgl.so
[LWJGL] [WARNING] Mismatch detected between the Java and native libraries.
[LWJGL] MemoryUtil accessor: MemoryAccessorUnsafe
java.lang.ClassNotFoundException: org.lwjgl.system.jemalloc.JEmallocAllocator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.lwjgl.system.MemoryManage.getInstance(MemoryManage.java:36)
	at org.lwjgl.system.MemoryUtil$LazyInit.<clinit>(MemoryUtil.java:76)
	at org.lwjgl.system.MemoryUtil.nmemAlloc(MemoryUtil.java:145)
	at org.lwjgl.system.MemoryUtil.memAlloc(MemoryUtil.java:163)
	at org.lwjgl.system.MemoryUtil.memASCII(MemoryUtil.java:1321)
	at org.lwjgl.system.MemoryUtil.memASCII(MemoryUtil.java:1306)
	at com.kellerkindt.vulkan.VulkanApplication.<clinit>(VulkanApplication.java:26)
	at com.kellerkindt.vulkan2d.Main.main(Main.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
[LWJGL] Failed to instantiate memory allocator: org.lwjgl.system.jemalloc.JEmallocAllocator
[LWJGL] MemoryUtil allocator: StdlibAllocator
[LWJGL] ThreadLocalUtil state: UnsafeState
[LWJGL] Loading library: glfw
[LWJGL] 	Found at: /tmp/lwjglmichael/3.0.1-build-35/libglfw.so
[LWJGL] 	Loaded from org.lwjgl.librarypath: /tmp/lwjglmichael/3.0.1-build-35/libglfw.so
[LWJGL] [WARNING] Mismatch detected between the Java and native libraries.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.nglfwSetErrorCallback(GLFW.java:853)
	at org.lwjgl.glfw.GLFW.glfwSetErrorCallback(GLFW.java:882)
	at org.lwjgl.glfw.GLFWErrorCallback.set(GLFWErrorCallback.java:111)
	at com.kellerkindt.vulkan.VulkanApplication.<init>(VulkanApplication.java:69)
	at com.kellerkindt.vulkan2d.Main.main(Main.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IllegalStateException: This function is not available.
	at org.lwjgl.system.Checks.checkFunctionAddress(Checks.java:94)
	at org.lwjgl.system.APIUtil.apiGetFunctionAddress(APIUtil.java:120)
	at org.lwjgl.glfw.GLFW$Functions.<clinit>(GLFW.java:620)
	... 10 more
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.kellerkindt</groupId>
    <artifactId>vulkan2d</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <lwjgl.version>3.0.1-SNAPSHOT</lwjgl.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl</artifactId>
            <version>${lwjgl.version}</version>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-glfw</artifactId>
            <version>${lwjgl.version}</version>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-vulkan</artifactId>
            <version>${lwjgl.version}</version>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-platform</artifactId>
            <version>${lwjgl.version}</version>
            <classifier>natives-linux</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-platform</artifactId>
            <version>${lwjgl.version}</version>
            <classifier>natives-windows</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-platform</artifactId>
            <version>${lwjgl.version}</version>
            <classifier>natives-osx</classifier>
        </dependency>
    </dependencies>



    <repositories>
        <repository>
            <id>lwjgl-nightly</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>


</project>
```

**Comment by Spasi** [comment]
The Maven dependencies are wrong:

- The `3.0.1-SNAPSHOT` version is invalid. `3.0.1` was promoted to `3.1.0` because of significant changes in that release. The current snapshot version is `3.1.2-SNAPSHOT`.
- The `lwjgl-platform` artifact does not exist anymore, starting with the `3.1.0` release.
- The native artifacts for `lwjgl` and `lwjgl-glfw` are missing.

It's very easy to fix the above issues. Visit the [build configurator](https://www.lwjgl.org/download), choose the Maven mode and the modules you need, then simply copy/paste the generated script in your `pom.xml`

**Comment by kellerkindt** [comment]
Woah. Thanks, thanks a lot :)
