### ISSUE TITLE
ExceptionInInitializerError when using OpenGL ES

### ISSUE THREAD

**Issue by Tobi29** [LWJGL/lwjgl3#276]
Calling certain GLES20 functions (presumably GLES30 ones as well, however not all do this) cause the following exception:
```
java.lang.ExceptionInInitializerError
	at org.lwjgl.opengles.GLES$ICDStatic.get(GLES.java:324)
	at org.lwjgl.opengles.GLES.getICD(GLES.java:291)
	at org.lwjgl.opengles.GLES20.glUniformMatrix4fv(GLES20.java:2509)
	at org.tobi29.scapes.engine.backends.lwjgl3.glfw.ContainerGLFW.initWindow(ContainerGLFW.kt:311)
	at org.tobi29.scapes.engine.backends.lwjgl3.glfw.ContainerGLFW.run(ContainerGLFW.kt:186)
	at org.tobi29.scapes.engine.ScapesEngine.run(ScapesEngine.kt:210)
	at org.tobi29.scapes.desktop.ScapesKt.main(Scapes.kt:94)
Caused by: java.lang.IllegalStateException: No GLESCapabilities instance has been set
	at org.lwjgl.opengles.GLES$ICDStatic$WriteOnce.<clinit>(GLES.java:333)
	... 7 more
```
(In this specific case I just did a dummy call to GLES20.glUniformMatrix4fv() right after calling GLES.createCapabilities() to check if this can be reproduced easily)

Looking and the code handling the capability instances in LWJGL I found the following:
https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/main/java/org/lwjgl/opengles/GLES.java#L157-L160
compared to
https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/main/java/org/lwjgl/opengl/GL.java#L228-L232
The former is missing that `icd.set(caps);` call (which appears to be the only codepath to call that set method, with the GLES equivalent there is no codepath at all it seems) and in fact manually doing that call through hacky reflection seems to fix the exception.

**Comment by Spasi** [comment]
Thanks, that call is indeed missing. Note that it only affects functions that accept Java arrays. You can use the equivalent calls with buffers until this is fixed in the next nightly build.
