### ISSUE TITLE
 The ' characters around the executable and arguments are not part of the command.

### ISSUE THREAD

**Issue by SpaceboyRoss01** [LWJGL/lwjgl3#371]
I was trying to compile LWJGL3 for myself, but when I ran `ant compile` it failed. Output:
```
[Generator] '-Dbinding.DISABLE_CHECKS=false'
[Generator] '-Dbinding.remotery=true'
[Generator] '-Dbinding.yoga=true'
[Generator] '-Dbinding.jawt=true'
[Generator] '-Dbinding.lmdb=true'
[Generator] '-Dbinding.lz4=true'
[Generator] '-Dbinding.spaceui=true'
[Generator] '-Dbinding.tootle=true'
[Generator] '-Dbinding.assimp=true'
[Generator] '-Dbinding.par=true'
[Generator] '-Dbinding.openvr=true'
[Generator] '-Dbinding.xxhash=true'
[Generator] '-Dbinding.odbc=true'
[Generator] '-Dbinding.glfw=true'
[Generator] '-Dbinding.nuklear=true'
[Generator] '-Dbinding.tinyexr=true'
[Generator] '-Dbinding.vulkan=true'
[Generator] '-Dbinding.stb=true'
[Generator] '-Dbinding.opengl=true'
[Generator] '-Dbinding.sse=true'
[Generator] '-Dbinding.opengles=true'
[Generator] '-Dbinding.rpmalloc=true'
[Generator] '-Dbinding.egl=true'
[Generator] '-Dbinding.nanovg=true'
[Generator] '-Dbinding.zstd=true'
[Generator] '-Dbinding.bgfx=true'
[Generator] '-Dbinding.nfd=true'
[Generator] '-Dbinding.opencl=true'
[Generator] '-Dbinding.jemalloc=true'
[Generator] '-Dbinding.tinyfd=true'
[Generator] '-Dbinding.openal=true'
[Generator] '-classpath'
[Generator] '/home/spaceboyross/lwjgl3/bin/classes/generator:/home/spaceboyross/lwjgl3/bin/classes/templates:/home/spaceboyross/lwjgl3/bin/libs/kotlinc/lib/kotlin-runtime.jar'
[Generator] 'org.lwjgl.generator.GeneratorKt'
[Generator] 'modules/lwjgl'
[Generator] 
[Generator] The ' characters around the executable and arguments are
[Generator] not part of the command.
[Generator] java.lang.IllegalStateException
[Generator] 	at org.lwjgl.generator.Generator.apply(Generator.kt:302)
[Generator] 	at org.lwjgl.generator.Generator.generateModule$generator(Generator.kt:345)
[Generator] 	at org.lwjgl.generator.GeneratorKt$$special$$inlined$let$lambda$1.run(Generator.kt:134)
[Generator] 	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
[Generator] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[Generator] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[Generator] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[Generator] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[Generator] Exception in thread "main" java.lang.RuntimeException: Generation failed
[Generator] 	at org.lwjgl.generator.GeneratorKt.main(Generator.kt:146)
```

**Comment by Spasi** [comment]
> -Dbinding.spaceui=true

Looks like you're working on new bindings there. There should be a directory:

`modules/lwjgl/spaceui/src/main/kotlin/spaceui/templates/`

that contains Kotlin templates. The exception happens because it's missing.
