### ISSUE TITLE
 java.lang.ClassNotFoundException: org.lwjgl.glfw.GLFWErrorCallback

### ISSUE THREAD

**Issue by matrximode** [LWJGL/lwjgl3#401]
bug

### Environment

* LWJGL version: `3.2.0` 
* LWJGL build #: `12`
* Java version: `10.0.2`
* Platform: `macOS`
* Module: `org.lwjgl.glfw.Callbacks`

### Description

It's been over 10 years since I touched java, I apologize if it is something obvious, but eclipse, and netbeans no longer match the "Getting Started" descriptions. I did not try to use IntelliJ. I am  trying to compile from CLI (bash terminal) at this point, and the following step appears to be working:

First I just put the HelloWorld.java file in the same folder as all the ".jars" from the zip. (I also tried it minus the doc and source .jars, seems irrelevant)

javac HelloWorld.java -classpath lwjgl-assimp-natives-macos.jar:./lwjgl-assimp.jar:./lwjgl-bgfx-natives-macos.jar:./lwjgl-bgfx.jar:./lwjgl-egl.jar:./lwjgl-glfw-natives-macos.jar:./lwjgl-glfw.jar:./lwjgl-jawt.jar:./lwjgl-jemalloc-natives-macos.jar:./lwjgl-jemalloc.jar:./lwjgl-lmdb-natives-macos.jar:./lwjgl-lmdb.jar:./lwjgl-lz4-natives-macos.jar:./lwjgl-lz4.jar:./lwjgl-nanovg-natives-macos.jar:./lwjgl-nanovg.jar:./lwjgl-natives-macos.jar:./lwjgl-nfd-natives-macos.jar:./lwjgl-nfd.jar:./lwjgl-nuklear-natives-macos.jar:./lwjgl-nuklear.jar:./lwjgl-odbc.jar:./lwjgl-openal-natives-macos.jar:./lwjgl-openal.jar:./lwjgl-opencl.jar:./lwjgl-opengl-natives-macos.jar:./lwjgl-opengl.jar:./lwjgl-opengles-natives-macos.jar:./lwjgl-opengles.jar:./lwjgl-openvr-natives-macos.jar:./lwjgl-openvr.jar:./lwjgl-par-natives-macos.jar:./lwjgl-par.jar:./lwjgl-remotery-natives-macos.jar:./lwjgl-remotery.jar:./lwjgl-rpmalloc-natives-macos.jar:./lwjgl-rpmalloc.jar:./lwjgl-sse-natives-macos.jar:./lwjgl-sse.jar:./lwjgl-stb-natives-macos.jar:./lwjgl-stb.jar:./lwjgl-tinyexr-natives-macos.jar:./lwjgl-tinyexr.jar:./lwjgl-tinyfd-natives-macos.jar:./lwjgl-tinyfd.jar:./lwjgl-tootle-natives-macos.jar:./lwjgl-tootle.jar:./lwjgl-vma-natives-macos.jar:./lwjgl-vma.jar:./lwjgl-vulkan-natives-macos.jar:./lwjgl-vulkan.jar:./lwjgl-xxhash-natives-macos.jar:./lwjgl-xxhash.jar:./lwjgl-yoga-natives-macos.jar:./lwjgl-yoga.jar:./lwjgl-zstd-natives-macos.jar:./lwjgl-zstd.jar:./lwjgl.jar

everything good so far.

but this is a problem
java -cp "./lwjgl.jar:." HelloWorld

Results in this error.
Hello LWJGL 3.2.0 build 12!
Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallback
	at HelloWorld.init(HelloWorld.java:37)
	at HelloWorld.run(HelloWorld.java:22)
	at HelloWorld.main(HelloWorld.java:112)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.glfw.GLFWErrorCallback
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 3 more

Is this a legit issue, or just user error.  I cannot find GLFWErrorCallback.

**Comment by matrximode** [comment]
I got lazy on that last CLI bit. Which brought up another issue, easily fixed.  This is what worked for me:

java -XstartOnFirstThread -cp "./lwjgl.jar:./lwjgl-assimp-natives-macos.jar:./lwjgl-assimp.jar:./lwjgl-bgfx-natives-macos.jar:./lwjgl-bgfx.jar:./lwjgl-egl.jar:./lwjgl-glfw-natives-macos.jar:./lwjgl-glfw.jar:./lwjgl-jawt.jar:./lwjgl-jemalloc-natives-macos.jar:./lwjgl-jemalloc.jar:./lwjgl-lmdb-natives-macos.jar:./lwjgl-lmdb.jar:./lwjgl-lz4-natives-macos.jar:./lwjgl-lz4.jar:./lwjgl-nanovg-natives-macos.jar:./lwjgl-nanovg.jar:./lwjgl-natives-macos.jar:./lwjgl-nfd-natives-macos.jar:./lwjgl-nfd.jar:./lwjgl-nuklear-natives-macos.jar:./lwjgl-nuklear.jar:./lwjgl-odbc.jar:./lwjgl-openal-natives-macos.jar:./lwjgl-openal.jar:./lwjgl-opencl.jar:./lwjgl-opengl-natives-macos.jar:./lwjgl-opengl.jar:./lwjgl-opengles-natives-macos.jar:./lwjgl-opengles.jar:./lwjgl-openvr-natives-macos.jar:./lwjgl-openvr.jar:./lwjgl-par-natives-macos.jar:./lwjgl-par.jar:./lwjgl-remotery-natives-macos.jar:./lwjgl-remotery.jar:./lwjgl-rpmalloc-natives-macos.jar:./lwjgl-rpmalloc.jar:./lwjgl-sse-natives-macos.jar:./lwjgl-sse.jar:./lwjgl-stb-natives-macos.jar:./lwjgl-stb.jar:./lwjgl-tinyexr-natives-macos.jar:./lwjgl-tinyexr.jar:./lwjgl-tinyfd-natives-macos.jar:./lwjgl-tinyfd.jar:./lwjgl-tootle-natives-macos.jar:./lwjgl-tootle.jar:./lwjgl-vma-natives-macos.jar:./lwjgl-vma.jar:./lwjgl-vulkan-natives-macos.jar:./lwjgl-vulkan.jar:./lwjgl-xxhash-natives-macos.jar:./lwjgl-xxhash.jar:./lwjgl-yoga-natives-macos.jar:./lwjgl-yoga.jar:./lwjgl-zstd-natives-macos.jar:./lwjgl-zstd.jar:./lwjgl.jar:." HelloWorld
