### ISSUE TITLE
Can't run the helloworld example

### ISSUE THREAD

**Issue by Samsung03** [LWJGL/lwjgl3#411]
### Environment

* LWJGL version: `3.2.0` 
* LWJGL build #: `12`
* Java version: `1.8.0_181`
* Platform: `Debian Linux(Raspbian) ARM`

### Description

Every time I try to run the HelloWorld example on the LWJGL website I get this error:

`run:
Hello LWJGL 3.2.0 build 12!
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl32.so
	at org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:61)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:99)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:88)
	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:77)
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:284)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at org.lwjgl.system.MemoryStack.stackGet(MemoryStack.java:661)
	at org.lwjgl.system.MemoryStack.stackPush(MemoryStack.java:670)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:40)
	at helloworld.HelloWorld.init(HelloWorld.java:39)
	at helloworld.HelloWorld.run(HelloWorld.java:24)
	at helloworld.HelloWorld.main(HelloWorld.java:114)
/home/Sam/.cache/netbeans/8.1/executor-snippets/run.xml:53: Java returned: 1
BUILD FAILED (total time: 3 seconds)
`
Could it be because i'm on ARM? If so, is support for ARM coming soon?

**Comment by kenzierocks** [comment]
ARM is still unsupported, see #206.

**Comment by Spasi** [comment]
LWJGL 3.2.3 supports ARM.

**Comment by Askmewho** [comment]
@Spasi great, But where are the shared libraries, not the jar ones?? 
the game ask for .so libraries

**Comment by Spasi** [comment]
@Askmewho you can use the [build customizer](https://www.lwjgl.org/customize) to get everything (in a .zip or via Maven/Gradle), or the [artifact browser](https://www.lwjgl.org/browse/release/3.2.3/linux) to download the shared libraries directly.
