### ISSUE TITLE
LibFFITest failing on local OS X Mavericks 10.9.5 

### ISSUE THREAD

**Issue by virtuoushub** [LWJGL/lwjgl3#43]
One of the LWJGL Core Tests, LibFFITest, is failing in my local environment.

### Environment:
Ant 1.94. , Java 1.8.0_25, Mac OS X 1.9.5
```bash
ant -version
Apache Ant(TM) version 1.9.4 compiled on April 29 2014
```

```bash
java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

```bash
sw_vers -productVersion 
10.9.5
```

### Steps to reproduce:

```bash
ant tests
```

### Expected Result:
```
tests:
    [Tests] [LWJGL] Version 3.0.0a | Mac OS X | x86_64
    [Tests] [LWJGL] MemoryUtil MemoryAccessor: MemoryAccessorUnsafe
    [Tests] [TestNG] Running:
    [Tests]   /Users/java/Documents/git/lwjgl3/config/tests.xml
    [Tests] 
    [Tests] 
    [Tests] ===============================================
    [Tests] LWJGL Core Tests
    [Tests] Total tests run: 20, Failures: 0, Skips: 0
    [Tests] ===============================================
    [Tests] 
    [Tests] [TestNG] Running:
    [Tests]   /Users/java/Documents/git/lwjgl3/config/tests_macosx.xml
    [Tests] 
    [Tests] 
    [Tests] ===============================================
    [Tests] LWJGL Platform Tests
    [Tests] Total tests run: 0, Failures: 0, Skips: 0
    [Tests] ===============================================
    [Tests]
```

### Actual Result:
```
    [Tests] [LWJGL] Version 3.0.0a | Mac OS X | x86_64
    [Tests] [LWJGL] MemoryUtil MemoryAccessor: MemoryAccessorUnsafe
    [Tests] [TestNG] Running:
    [Tests]   /Users/java/Documents/git/lwjgl3/config/tests.xml
    [Tests] 
    [Tests] 
    [Tests] ===============================================
    [Tests] LWJGL Core Tests
    [Tests] Total tests run: 20, Failures: 1, Skips: 0
    [Tests] ===============================================
    [Tests] 
    [Tests] [TestNG] Running:
    [Tests]   /Users/java/Documents/git/lwjgl3/config/tests_macosx.xml
    [Tests] 
    [Tests] 
    [Tests] ===============================================
    [Tests] LWJGL Platform Tests
    [Tests] Total tests run: 0, Failures: 0, Skips: 0
    [Tests] ===============================================
    [Tests] 
    [Tests] The tests failed.
```
I looked into the name and cause of the one failed test:

```java
org.lwjgl.system.libffi.LibFFITest
testLibFFI
java.lang.IllegalStateException: Please run the JVM with -XstartOnFirstThread.
	at org.lwjgl.system.macosx.EventLoop.checkFirstThread(EventLoop.java:20)
	at org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:426)
	at org.lwjgl.system.libffi.LibFFITest.createGLFWWindow(LibFFITest.java:114)
	at org.lwjgl.system.libffi.LibFFITest.testLibFFI(LibFFITest.java:29)
... Removed 23 stack frames
```

**Comment by Spasi** [comment]
Resolved with #44.
