### ISSUE TITLE
Threaded GLFW: Never a GL Context?

### ISSUE THREAD

**Issue by gudenau** [LWJGL/lwjgl3#452]
### Environment

* LWJGL version: `3.2.1` 
* LWJGL build #: `12`
* Java version: `11.0.2`
* Platform: `Linux`
* Module: `GLFW/GL`

### Description
While splitting a program into multiple threads, one for GLFW events and the other for rendering/game logic there is never a valid GL context in the worker thread, despite calling `GLFW.glfwMakeContextCurrent(windowHandle);` from the worker.

This causes one of three things to happen from my testing:

- Causes an exception to be thrown from X
```
glfwInit: true
glfwCreateWindow: 139730728745936
glfwTerminate
Returned handle: 139730728745936
glfwMakeContextCurrent
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  178
  Current serial number in output stream:  178
```
- Causes `GL.createCapabilities` to throw an exception
```
glfwInit: true
glfwCreateWindow: 140400878164096
glfwTerminate
Returned handle: 140400878164096
glfwMakeContextCurrent
Exception in thread "new main" java.lang.IllegalStateException: There is no OpenGL context current in the current thread.
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:378)
	at org.lwjglx.debug.opengl.GL.createCapabilities(GL.java:52)
	at org.lwjglx.debug.$Proxy$14.createCapabilities7(Unknown Source)
	at net.gudenau.game.Window.<init>(Window.java:45)
	at net.gudenau.game.Game.run(Game.java:13)
	at net.gudenau.game.Game.lambda$main$0(Game.java:25)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
- Causes the JVM to crash
```
glfwInit: true
glfwCreateWindow: 140042650020512
glfwTerminate
Returned handle: 140042650020512
glfwMakeContextCurrent
Exception in thread "new main" java.lang.IllegalStateException: There is no OpenGL context current in the current thread.
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:378)
	at net.gudenau.game.Window.<init>(Window.java:32)
	at net.gudenau.game.Game.run(Game.java:6)
	at net.gudenau.game.Game.lambda$main$0(Game.java:18)
	at java.base/java.lang.Thread.run(Thread.java:834)
-- Native dump snipped, just had ASLR addresses and no names/symbols --
 ```

I have stepped though the code several times and verified the Threads and window states are consistent between threads.

Unfortunately because of the threading and synchronization mechanisms I can't think of a way to make this much smaller than this. Sorry about that.

net.gudenau.game.Game
```Java
package net.gudenau.game;

public class Game implements Runnable{
    @Override
    public void run(){
        try(var window = new Window(640, 480, "Game")){
            window.makeCurrent();
            window.setVisible(true);
            while(!window.shouldClose()){
                window.swap();
                GlfwHelper.poll();
            }
        }
        GlfwHelper.stop();
    }
    
    public static void main(String[] arguments){
        GlfwHelper.start(()->new Game().run());
    }
}
```

net.gudenau.game.Window
```Java
package net.gudenau.game.Window;

import org.lwjgl.glfw.GLFW;
import org.lwjgl.opengl.GL;
import org.lwjgl.opengl.GLCapabilities;

import static org.lwjgl.system.MemoryUtil.NULL;

public class Window{
    private final GLCapabilities capabilities;
    
    private long handle;
    
    public Window(int width, int height, CharSequence title){
        handle = GlfwHelper.runSync(()->{
            GLFW.glfwDefaultWindowHints();
            GLFW.glfwWindowHint(GLFW.GLFW_SAMPLES, 1);
            GLFW.glfwWindowHint(GLFW.GLFW_CONTEXT_VERSION_MAJOR, 3);
            GLFW.glfwWindowHint(GLFW.GLFW_CONTEXT_VERSION_MINOR, 3);
            GLFW.glfwWindowHint(GLFW.GLFW_OPENGL_FORWARD_COMPAT, GLFW.GLFW_TRUE);
            GLFW.glfwWindowHint(GLFW.GLFW_OPENGL_PROFILE, GLFW.GLFW_OPENGL_CORE_PROFILE);
            GLFW.glfwWindowHint(GLFW.GLFW_VISIBLE, GLFW.GLFW_FALSE);
            GLFW.glfwWindowHint(GLFW.GLFW_RESIZABLE, GLFW.GLFW_FALSE);
            long result = GLFW.glfwCreateWindow(width, height, title, NULL, NULL);
            System.out.printf("glfwCreateWindow: %d\n", result);
            return result;
        });
        System.out.printf("Returned handle: %d\n", handle);
    
        System.out.println("glfwMakeContextCurrent");
        GLFW.glfwMakeContextCurrent(handle);
        capabilities = GL.createCapabilities(true);
    }
    
    public void setVisible(boolean visible){
        if(visible){
            GlfwHelper.runAsync(()->{
                System.out.println("glfwShowWindow");
                GLFW.glfwShowWindow(handle);
            });
        }else{
            GlfwHelper.runAsync(()->{
                System.out.println("glfwHideWindow");
                GLFW.glfwHideWindow(handle);
            });
        }
    }
    
    public boolean shouldClose(){
        var result = GLFW.glfwWindowShouldClose(handle);
        System.out.printf("glfwWindowShouldClsoe:  %s\n", result ? "true" : "false");
        return result;
    }
    
    public void swap(){
        System.out.println("glfwSwapBuffers");
        GLFW.glfwSwapBuffers(handle);
    }
    
    public void makeCurrent(){
        System.out.println("glfwMakeContextCurrent");
        GLFW.glfwMakeContextCurrent(handle);
        GL.setCapabilities(capabilities);
    }
    
    public void destroy(){
        GlfwHelper.runSync(()->{
            System.out.println("glfwDestroyWindow");
            GLFW.glfwDestroyWindow(handle);
        });
    }
}
```

net.gudenau.game.GlfwHelper
```Java
package net.gudenau.game;

import java.util.LinkedList;
import java.util.Queue;
import org.lwjgl.glfw.GLFW;
import org.lwjgl.glfw.GLFWErrorCallback;

public class GlfwHelper{
    private static final Queue<Runnable> workQueue = new LinkedList<>();
    private static volatile boolean shouldRun = true;
    private static volatile Thread worker;
    
    public static void start(Runnable runnable){
        worker = Thread.currentThread();
        new Thread(runnable, "new main").start();
        GLFWErrorCallback.createPrint(System.err).set();
        System.out.printf("glfwInit: %s\n", GLFW.glfwInit() ? "true" : "false");
        runEventLoop();
        System.out.println("glfwTerminate");
        GLFW.glfwTerminate();
        GLFW.glfwSetErrorCallback(null).free();
    }
    
    private static void runEventLoop(){
        while(shouldRun && !workQueue.isEmpty()){
            Runnable work;
            synchronized(workQueue){
                work = workQueue.poll();
                if(work == null){
                    try{
                        workQueue.wait();
                    }catch(InterruptedException e){
                        return;
                    }
                }else{
                    work.run();
                }
            }
        }
    }
    
    public static void runAsync(Runnable runnable){
        synchronized(workQueue){
            workQueue.add(runnable);
            workQueue.notify();
        }
    }
    
    public static void runSync(Runnable runnable){
        final Runnable newRunnable = ()->{
            synchronized(runnable){
                runnable.run();
                runnable.notify();
            }
        };
        
        synchronized(runnable){
            synchronized(workQueue){
                workQueue.add(newRunnable);
                workQueue.notify();
            }
            try{
                runnable.wait();
            }catch(InterruptedException ignored){}
        }
    }
    
    public static <T> T runSync(RunnableResult<T> runnable){
        final Object[] result = new Object[1];
        runSync(()->{
            result[0] = runnable.run();
        });
        //noinspection unchecked
        return (T)result[0];
    }
    
    public static void poll(){
        runAsync(()->{
            System.out.println("glfwPollEvents");
            GLFW.glfwPollEvents();
        });
    }
    
    public static void stop(){
        shouldRun = false;
        worker.notify();
    }
    
    public interface RunnableResult<T>{
        T run();
    }
}
```

**Comment by kenzierocks** [comment]
Your `glfwInit` call isn't guaranteed to occur before the runnable you pass starts. So that's probably part of what's happening.

**Comment by gudenau** [comment]
How is that the case? Before the GLFW thread can process events it calls `glfwInit`, no runnable can run before that.

**Comment by kenzierocks** [comment]
Ah, I missed the details of `runSync`. I'm not sure then, I'd have to try running it myself.

**Comment by httpdigest** [comment]
The problem is in this piece of code:
```
worker = Thread.currentThread();
new Thread(runnable, "new main").start(); // <- Thread starts at some point
GLFWErrorCallback.createPrint(System.err).set();
System.out.printf("glfwInit: %s\n", GLFW.glfwInit() ? "true" : "false");
runEventLoop(); // <- event loop may terminate immediately due to no elements to process
System.out.println("glfwTerminate");
GLFW.glfwTerminate();
GLFW.glfwSetErrorCallback(null).free();
```
together with this:
```
private static void runEventLoop(){
  while(shouldRun && !workQueue.isEmpty()){ // <- may return false if no items in workQueue
```
Due to the `new Thread(runnable, "new main").start();` thread starting at some point asynchronous to the calling code and your runEventLoop() immediately terminating, you are terminating glfw and all windows/contexts via `glfwTerminate()`.
Even your stdout messages that you posted tells that you are always calling glfwTerminate(). You cannot call glfwTerminate() and expect everything to still work.

**Comment by gudenau** [comment]
Oh my god, I am an idiot. Sorry about that.
