### ISSUE TITLE
glViewport works on Linux but fails on Windows

### ISSUE THREAD

**Issue by VortexAcherontic** [LWJGL/lwjgl3#466]
I think this is more a question than a bug.

Here is the situation:

```
 public boolean init() {
        GLFWErrorCallback.createPrint(System.err).set();
        if ( !glfwInit() ){
            SELogger.get().dispatchMsg(this, SELogger.SELogType.ERROR, new String[]{"Unable to initialize GLFW"}, true);
            return false;
        }
        glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);
        glfwWindowHint(GLFW_RESIZABLE, GLFW_TRUE);
        window = glfwCreateWindow(windowW, windowH, windowTitle, NULL, NULL);
        if ( window == NULL ){
            SELogger.get().dispatchMsg(this, SELogger.SELogType.ERROR, new String[]{"Failed to create the GLFW window"}, true);
            return false;
        }
        glfwMakeContextCurrent(window);
        
        glfwSetMouseButtonCallback(window, (window, key, action, mods) -> {
            
        });

        glfwSetWindowSizeCallback(window, (window, w, h) -> {
            calcWindowProps(w, h);
        });
        
        try ( MemoryStack stack = stackPush() ) {
            IntBuffer pWidth = stack.mallocInt(1);
            IntBuffer pHeight = stack.mallocInt(1);
            glfwGetWindowSize(window, pWidth, pHeight);
            GLFWVidMode vidmode = glfwGetVideoMode(glfwGetPrimaryMonitor());
            glfwSetWindowPos(window, (vidmode.width() - pWidth.get(0)) / 2, (vidmode.height() - pHeight.get(0)) / 2);
        }

        glfwSwapInterval(0);
        glfwShowWindow(window);
        createCapabilities();
        glClearColor(0.0f, 0.0f, 0.0f, 0.0f);
        calcWindowProps(windowW, windowH);
        return true;
    }

    private void calcWindowProps(int w, int h){
        aspectRatio = (float)w/(float)h;
        windowW = w;
        windowH = h;
        glViewport(0, 0, windowW, windowH); //line 93
    }
```

This code is working on Linux (which is my main development machine) as it should. A window opens and stuff is rendered after the init.
On windows on the other hand it's craching with this message:

````
FATAL ERROR in native method: Thread[Thread-0,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.glViewport(Native Method)
	at org.lwjgl.opengl.GL11.glViewport(GL11.java:8021)
	at de.zray.renderbackends.opengl.GLRenderer.calcWindowProps(GLRenderer.java:93)
	at de.zray.renderbackends.opengl.GLRenderer.lambda$init$1(GLRenderer.java:70)
	at de.zray.renderbackends.opengl.GLRenderer$$Lambda$44/0x0000000801255c40.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWWindowSizeCallbackI.callback(GLFWWindowSizeCallbackI.java:35)
	at org.lwjgl.system.JNI.invokePV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwShowWindow(GLFW.java:2528)
	at de.zray.renderbackends.opengl.GLRenderer.init(GLRenderer.java:82)
	at de.zray.se.MainThread.lambda$loop$0(MainThread.java:71)
	at de.zray.se.MainThread$$Lambda$42/0x0000000801256c40.run(Unknown Source)
	at java.lang.Thread.run(java.base@12.0.1/Thread.java:835)
````

And I have no cue why.
For my undestanding the context is current (on Linux it's working) and there should be no reason why this should not work.

As I first encountered issues after my upgrade from LWJGL 2 to 3.1.1 the whle Java VM was charching with a core dump.
So I upgraded to 3.2.2 and from JDK 10 to 12 and from Netbeans 9 to 11 which did not realy solved the issue like you see above. Now the VM is not crashing with a core dump but it still has issues on windows. And I wonder why. What am I missing?

Maybe it has something to do with my feature test function I call before:

````
public boolean featureTest() {
        GLFWErrorCallback.createPrint(System.err).set();
        if (!glfwInit()){
            SELogger.get().dispatchMsg(this, SELogger.SELogType.ERROR, new String[]{"Unable to initialize GLFW"}, true);
            return false;
        }
        glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);
        window = glfwCreateWindow(windowW, windowH, windowTitle, NULL, NULL);
        if ( window == NULL ){
            SELogger.get().dispatchMsg(this, SELogger.SELogType.ERROR, new String[]{"Failed to create the GLFW window"}, true);
            return false;
        }

        glfwMakeContextCurrent(window);
        GLCapabilities caps = GL.createCapabilities();
        
        boolean glSupported = caps.OpenGL15;
        if(glSupported){
            SELogger.get().dispatchMsg(this, SELogger.SELogType.INFO, new String[]{"OpenGL 1.5 supported!"}, false);
        } else {
            SELogger.get().dispatchMsg(this, SELogger.SELogType.ERROR, new String[]{"OpenGL 1.5 not supported!"}, false);
        }
        
        glfwFreeCallbacks(window);
        glfwDestroyWindow(window);
        glfwTerminate();
        glfwSetErrorCallback(null).free();
        window = -1;
        
        return glSupported;
    }
````

But I'm not sure, again, on Linux it works.

I would appretiate any help here 😄

**Comment by kenzierocks** [comment]
Perhaps Windows is not providing a OpenGL 2+ context for some reason? You might want to try printing out the OpenGL version.

**Comment by VortexAcherontic** [comment]
According to GPU Cpas Viewer it supports up to OpenGL 4.6

````
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GT 730M/PCIe/SSE2
GL_VERSION: 4.6.0 NVIDIA 417.35
GL_MAX_TEXTURE_SIZE: 16384
GL_MAX_COLOR_ATTACHMENTS: 8
GL_MAX_TEXTURE_IMAGE_UNITS: 32
GL_MAX_TESS_GEN_LEVEL: 64
GL_WARP_SIZE_NV: 32
GL_WARPS_PER_SM_NV: 64
GL_SM_COUNT_NV: 2
````

Or did you ment a more detailed extention list? 😄

**Comment by kenzierocks** [comment]
No, I meant from inside your program -- what version is GLFW actually getting, and is it a compatibility profile or a core profile. GLFW can take odd OpenGL options if you don't specify the window hints.

**Comment by VortexAcherontic** [comment]
The program craches before it reaches ``GL.createCapabilities();`` so I guess it's not getting any version?
Sorry if I am confused ^^"

**Comment by kenzierocks** [comment]
Oh, then that's your problem -- if you don't call `createCapabilities()`, then there's no GL function pointers available. You'll need to call that first.

**Comment by VortexAcherontic** [comment]
You're m hero! That did the trick 😄 

But still funny that it worked with Linux o.O

It's now like this:

````
````
