### ISSUE TITLE
Multiple package x64 not supported by java modules

### ISSUE THREAD

**Issue by Ealrann** [LWJGL/lwjgl3#479]
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build #: `SNAPSHOT 5`
* Java version: `11.0.3`
* Platform: `Linux`
* Module: `core`

### Description
Hello,

I just gave a try to the 3.2.3 branch, but it appears that `gradle build` doesn't work anymore for me. 

```
java.lang.LayerInstantiationException: Package x64 in both module org.lwjgl.stb.natives and module org.lwjgl.natives
        at java.base/jdk.internal.module.ModuleBootstrap.checkSplitPackages(ModuleBootstrap.java:470)
        at java.base/jdk.internal.module.ModuleBootstrap.boot(ModuleBootstrap.java:384)
        at java.base/java.lang.ClassLoader.initializeClassLoaders(ClassLoader.java:224)
        at java.base/java.lang.Thread.initialize(Thread.java:428)
        at java.base/java.lang.Thread.<init>(Thread.java:153)

```

I think that the error is due to multiples package that have the same name ("x64"), Java 9 modules doesn't allow that. 

Here a little demo project helping reproduce the problem : simply clone it and make a `gradle build`.

https://github.com/Ealrann/testLWJGL323

**Comment by Spasi** [comment]
@Ealrann Thank you!
