### ISSUE TITLE
DriftFX broken

### ISSUE THREAD

**Issue by Janrupf** [LWJGL/lwjgl3#550]
### Environment

* LWJGL version:  commit [1ffb2e7](https://github.com/LWJGL/lwjgl3/tree/1ffb2e773de303b28840a41fd653fdf3ebeccf31) (latest as of opening this issue)
* LWJGL build #: N/A
* Java version: `1.8 (OpenJDK)`
* Platform: `Linux` (probably all, only linux tested)
* Module: `driftfx`

### Description

Apparently, the DriftFX native library is missing a method or is missing entirely, which results in the following Stacktrace:
```
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: org.eclipse.fx.drift.internal.NativeAPI.nInitialize()V
	at org.eclipse.fx.drift.internal.NativeAPI.nInitialize(Native Method)
	at org.eclipse.fx.drift.internal.NativeAPI.Initialize(NativeAPI.java:111)
	at org.eclipse.fx.drift.internal.NativeAPI.<clinit>(NativeAPI.java:27)
	at org.eclipse.fx.drift.internal.GraphicsPipelineUtil.initialize(GraphicsPipelineUtil.java:250)
	at org.eclipse.fx.drift.DriftFXSurface.initialize(DriftFXSurface.java:300)
	at org.eclipse.fx.drift.DriftFXSurface.initialize(DriftFXSurface.java:327)
	at org.lwjgl.demo.driftfx.HelloDriftFX.start(HelloDriftFX.java:39)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$10(GtkApplication.java:245)
	... 1 more
Exception running application org.lwjgl.demo.driftfx.HelloDriftFX
```

### Further information
This does not just effect the current commit, but also the snapshot build `3.2.4-SNAPSHOT`

**Comment by Spasi** [comment]
Thanks @Janrupf!

The Linux binary was not exporting JNI symbols from `org.eclipse.fx.drift.*`, this has been fixed now.
