### ISSUE TITLE
Failed to locate library: libGLESv2.dll

### ISSUE THREAD

**Issue by zhoyq** [LWJGL/lwjgl3#575]
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build #: `13`
* Java version: `jdk14.0.1_x64`
* Platform: `Windows`
* Module: `opengles`

### Description

```log
[LWJGL] 	GLESv2.dll not found in system paths
[LWJGL] Failed to load a library. Possible solutions:
	a) Install the library or the driver that provides the library.
	b) Ensure that the library is accessible from the system library paths.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: libGLESv2.dll
	at org.lwjgl.system.Library.loadNative(Library.java:324)
	at org.lwjgl.system.Library.loadNative(Library.java:411)
	at org.lwjgl.system.Library.loadNative(Library.java:378)
	at org.lwjgl.opengles.GLES.create(GLES.java:89)
	at org.lwjgl.opengles.GLES.<clinit>(GLES.java:67)
	at org.lwjgl.opengles.GLES20.<clinit>(GLES20.java:327)
```

i want to konw it's provided by a native jar?  or just install by myself?

**Comment by Spasi** [comment]
EGL and OpenGL ES implementations are not provided by LWJGL. Drivers need to be installed separately. There also exists software that emulates EGL/GLES over the native APIs of your development platform (e.g. [ANGLE](https://github.com/google/angle)).

**Comment by zhoyq** [comment]
thanks.
