### ISSUE TITLE
GL20.glUniformMatrix4fv() does not work

### ISSUE THREAD

**Issue by Monniasza** [LWJGL/lwjgl3#579]
Reporting a bug?
----------------
First, replace the values in quotes below:

### Environment

* LWJGL version: `2.9.3` 
* Java version: `java.version`
* Platform: `Windows`
* Module: `core`
* IDE: `Eclipse Photon`

### Description
GL20.glUniformMatrix4fv() is required to transform 3D objects using GPU (CPU would be too slow). So, if it doesn't work, then objects can't be transformed.

### Steps to reproduce
Call `GL20.glUniformMatrix4fv(int location, boolean transpose, FloatBuffer value)` with valid values.
Create `FloatBuffer matrixBuffer` using `Matrix.get(matrixBuffer)`, where `matrixBuffer` is initially fresh 16-position `FloatBuffer`

### Expected results
Method finishes without errors

### Actual result
Method creates `NoSuchMethodError` (not `NoSuchMethodException`)
```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: org.lwjgl.opengl.GL20.glUniformMatrix4fv(IZLjava/nio/FloatBuffer;)V
	at mmb.render.flight.ShaderProgram.loadMatrix(ShaderProgram.java:117)
	at mmb.render.flight.StaticShader.loadTransformaionMatrix(StaticShader.java:42)
	at mmb.render.flight.Renderer.render(Renderer.java:29)
	at mmb.render.flight.Flight3.run(Flight3.java:91)
	at mmb.ui.window.MainMenu$4.actionPerformed(MainMenu.java:78)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by httpdigest** [comment]
The issue here is that at runtime you are having LWJGL 2 jars in the classpath whereas at compiletime you seem to use LWJGL 3 (hence compiling seemed to have worked, but linking the method call at runtime did not). The method is called `glUniformMatrix4` in LWJGL 2 but `glUniformMatrix4fv` (like the native C function) in LWJGL 3.
