### ISSUE TITLE
UnsatisfiedLinkingError when trying to run the "Get Started" Code Sample from the site

### ISSUE THREAD

**Issue by PhoenixXKN** [LWJGL/lwjgl3#597]
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build #: `13`
* Java version: `14.0.1`
* Platform: `Windows`
* Module: core|lgfw|opengl

### Description
When i tried compiling the sample from [the "getting started" page](https://www.lwjgl.org/guide), it worked, but after running it, i got this error message:
```
[LWJGL] Version: 3.2.3 build 13
[LWJGL] 	 OS: Windows 10 v10.0
[LWJGL] 	JRE: 14.0.1 amd64
[LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v14.0.1+7 by Oracle Corporation
[LWJGL] Loading JNI library: lwjgl
[LWJGL] 	Module: org.lwjgl
[LWJGL] 	windows/x64/org/lwjgl/lwjgl.dll not found in java.library.path=C:\Program Files\Java\jdk-14.0.1\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:/Program Files/AdoptOpenJDK/jre-14.0.1.7-hotspot/bin/client;C:/Program Files/AdoptOpenJDK/jre-14.0.1.7-hotspot/bin;C:\Program Files\AdoptOpenJDK\jre-14.0.1.7-hotspot\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\TXE Components\iCLS\;C:\Program Files\Intel\TXE Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\TXE Components\DAL\;C:\Program Files (x86)\Intel\TXE Components\DAL\;C:\Program Files\Intel\TXE Components\IPT\;C:\Program Files (x86)\Intel\TXE Components\IPT\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Users\Groß L\AppData\Local\bin\NASM;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Python27;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\Microsoft Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\MinGW\bin;C:\Program Files\CMake\bin;C:\Program Files (x86)\Intel\TXE Components\iCLS\;C:\Program Files\Intel\TXE Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\TXE Components\DAL\;C:\Program Files (x86)\Intel\TXE Components\DAL\;C:\Program Files\Intel\TXE Components\IPT\;C:\Program Files (x86)\Intel\TXE Components\IPT\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Users\Groß L\AppData\Local\bin\NASM;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\CMake\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\nodejs\;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\TXE Components\iCLS\;C:\Program Files\Intel\TXE Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\;C:\Users\lion\.dotnet\tools;C:\Users\Lion\AppData\Roaming\npm;C:\Use;C:\WINDOWS\System32;;.
[LWJGL] 	lwjgl.dll not found in java.library.path
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
	at org.lwjgl.system.Library.loadSystem(Library.java:162)
	at org.lwjgl.system.Library.loadSystem(Library.java:62)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
	at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:41)
	at MainGame.init(MainGame.java:38)
	at MainGame.run(MainGame.java:23)
	at MainGame.main(MainGame.java:116)
```
I am using eclipse, if that helps. What did i do wrong/how can i fix this? The .jar files i linked are lwjgl.jar, lwjgl-glfw.jar and lwjgl-opengl.jar.

**Comment by scaventz** [comment]
Hi, lPhoenixXKN , I think maybe you forgot to add wjgl-natives-windows.jar to your classpath ?

**Comment by PhoenixXKN** [comment]
Yes, this fixed it. I was confused why it told me a .dll was missing, that's why i didn't consider adding that file.
