### ISSUE TITLE
[DriftFX] [lwjgl-driftfx] Applications should not extend the Node class directly.

### ISSUE THREAD

**Issue by Aloento** [LWJGL/lwjgl3#617]
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[C] [ INFO] x\src\main\c\src\TransferModeManager.cpp: 87 - driftfx::internal::TransferModeManager::RegisterTransferMode                                         Registering TransferMode Instance 'LegacyWinFallback' as 0
[C] [ INFO] x\src\main\c\src\TransferModeManager.cpp: 87 - driftfx::internal::TransferModeManager::RegisterTransferMode                                         Registering TransferMode Instance 'MainMemory' as 1
[C] [ INFO] x\src\main\c\src\TransferModeManager.cpp: 87 - driftfx::internal::TransferModeManager::RegisterTransferMode                                         Registering TransferMode Instance 'NVDXInterop' as 2
[C] [ INFO] x\src\main\c\src\TransferModeManager.cpp: 87 - driftfx::internal::TransferModeManager::RegisterTransferMode                                         Registering TransferMode Instance 'NoOp' as 3
[C] [ INFO] driftfx\src\main\c\src\Configuration.cpp: 59 - driftfx::internal::Configuration::Initialize                                                         Loaded native driftfx configuration:
[C] [ INFO] driftfx\src\main\c\src\Configuration.cpp: 60 - driftfx::internal::Configuration::Initialize                                                         debug = 0
[C] [ INFO] driftfx\src\main\c\src\Configuration.cpp: 61 - driftfx::internal::Configuration::Initialize                                                         logLevel = 1
[C] [ INFO] driftfx\src\main\c\src\Configuration.cpp: 62 - driftfx::internal::Configuration::Initialize                                                         useWinFallback = 0
D3D0ExContext created!
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1071)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.UnsupportedOperationException: Applications should not extend the Node class directly.
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.getHelper(NodeHelper.java:76)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
	at javafx.graphics/javafx.scene.Node.updateGeomBounds(Node.java:3844)
	at javafx.graphics/javafx.scene.Node.getGeomBounds(Node.java:3806)
	at javafx.graphics/javafx.scene.Node.getLocalBounds(Node.java:3754)
	at javafx.graphics/javafx.scene.Node.updateTxBounds(Node.java:3908)
	at javafx.graphics/javafx.scene.Node.getTransformedBounds(Node.java:3700)
	at javafx.graphics/javafx.scene.Node$MiscProperties$2.computeBounds(Node.java:6802)
	at javafx.graphics/javafx.scene.Node$LazyBoundsProperty.get(Node.java:9779)
	at javafx.graphics/javafx.scene.Node$LazyBoundsProperty.get(Node.java:9749)
	at javafx.base/javafx.beans.binding.ObjectExpression.getValue(ObjectExpression.java:49)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.addListener(ExpressionHelper.java:53)
	at javafx.graphics/javafx.scene.Node$LazyBoundsProperty.addListener(Node.java:9758)
	at javafx.base/javafx.beans.binding.ObjectBinding.bind(ObjectBinding.java:108)
	at javafx.base/javafx.beans.binding.Bindings$6.<init>(Bindings.java:352)
	at javafx.base/javafx.beans.binding.Bindings.createObjectBinding(Bindings.java:350)
	at org.eclipse.fx.drift.internal.BaseScreenObserver.<init>(BaseScreenObserver.java:87)
	at org.eclipse.fx.drift.internal.ScreenObserver.<init>(ScreenObserver.java:11)
	at org.eclipse.fx.drift.BaseDriftFXSurface.init(BaseDriftFXSurface.java:119)
	at org.eclipse.fx.drift.DriftFXSurface.<init>(DriftFXSurface.java:70)
	at org.lwjgl.demo.driftfx.HelloDriftFX.start(HelloDriftFX.java:43)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run$$$capture(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	... 1 more
Exception running application org.lwjgl.demo.driftfx.HelloDriftFX
[C] [ INFO] x\src\main\c\src\gl\wgl\WGLGLContext.cpp:268 - driftfx::internal::gl::wgl::WGLGLContext::createGL                                                   Created OpenGL Context 0000000000010001: 4.1.0 - Build 27.20.100.8935 ( shared: 0000000000000000 )
[C] [ INFO] x\src\main\c\src\gl\wgl\WGLGLContext.cpp:268 - driftfx::internal::gl::wgl::WGLGLContext::createGL                                                   Created OpenGL Context 0000000000010002: 4.1.0 - Build 27.20.100.8935 ( shared: 0000000000010001 )

https://github.com/LWJGL/lwjgl3/blob/2224408833566ccfc2323ac6ac66d720dc74639e/modules/samples/src/test/java/org/lwjgl/demo/driftfx/HelloDriftFX.java#L43

**Comment by XingRay** [comment]
Hi, I encountered this error when using GraalVM JDK 21: "Applications should not extend the Node class directly." After some investigation, I discovered that this issue arises because DriftFX utilizes "Multi-Release JAR Files" (see https://openjdk.org/jeps/238). However, when running my application (via java -jar app.jar), the JDK fails to recognize the correct version and instead executes version 8 code rather than version 11.

I couldn't find a direct solution to resolve this issue, but I did discover a workaround:

Download the DriftFX JAR (org.eclipse.fx.drift-1.0.0.jar).
Unzip it to a folder.
Copy and replace the contents from org.eclipse.fx.drift-1.0.0\META-INF\versions\11\org to org.eclipse.fx.drift-1.0.0\org.
Zip the folder back into a JAR (simply creating a zip file and renaming it to org.eclipse.fx.drift-1.0.0.jar is sufficient). Ensure the file structure remains the same as the original.
Import this "fake Multi-Release JAR File" into your project, like so:
kotlin
Copy code
// implementation("org.eclipse.fx:org.eclipse.fx.drift:1.0.0")
implementation(files("libs/org.eclipse.fx.drift-1.0.0.jar"))
Build and run your project.
This workaround resolved the issue for me, but I hope someone can provide a more permanent solution.
