### ISSUE TITLE
HelloWorld doesn't work on Surface Pro X

### ISSUE THREAD

**Issue by adiantek** [LWJGL/lwjgl3#636]
* LWJGL build #: 3.3.0 build 10
* Java version: jdk-16-ea+19-windows-aarch64
openjdk version "16-ea" 2020-10-09
OpenJDK Runtime Environment Microsoft (build 16-ea+19-windows-aarch64)
OpenJDK 64-Bit Server VM Microsoft (build 16-ea+19-windows-aarch64, mixed mode)   

* Platform: Windows aarch64
* Module: core

### Description

When I'm running HelloWorld from https://www.lwjgl.org/guide I'm getting an error:

    Hello LWJGL 3.3.0 build 10!
    Exception in thread "main" java.lang.RuntimeException: Failed to prepare the libffi closure
            at org.lwjgl.system.Callback.create(Callback.java:168)
            at org.lwjgl.system.Callback.<init>(Callback.java:108)
            at org.lwjgl.glfw.GLFWErrorCallback.<init>(GLFWErrorCallback.java:60)
            at org.lwjgl.glfw.GLFWErrorCallback$1.<init>(GLFWErrorCallback.java:97)
            at org.lwjgl.glfw.GLFWErrorCallback.createPrint(GLFWErrorCallback.java:97)
            at example.App.init(App.java:39)
            at example.App.run(App.java:24)
            at example.App.main(App.java:114)

I printed errcode and errcode = FFI_BAD_ABI (2). I don't know how to fix it, but if you want I can make some tests with lwjgl on Surface Pro X. When I tried to run Minecraft 1.16.5 with lwjgl 3.3.0 build 10 I got the same error:

    ---- Minecraft Crash Report ----
    // This doesn't make any sense!
    
    Time: 25.03.2021, 01:36
    Description: Initializing game
    
    java.lang.RuntimeException: Failed to prepare the libffi closure: 2
    at org.lwjgl.system.Callback.create(Callback.java:168)
    at org.lwjgl.system.CallbackI.address(CallbackI.java:25)
    at org.lwjgl.system.MemoryUtil.memAddressSafe(MemoryUtil.java:850)
    at org.lwjgl.glfw.GLFW.glfwSetErrorCallback(GLFW.java:1197)
    at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:69)
    at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:1060)
    at djz.<init>(SourceFile:458)
    at net.minecraft.client.main.Main.main(SourceFile:177)

PS. I tested org.lwjgl.demo.openal.ALCDemo and it works fine, HelloAssimp too. EGLDemo and GLFWDemo, EasyFont requires fix with libffi.
org.lwjgl.demo.opencl.CLDemo throwed me:

    Exception in thread "main" java.lang.RuntimeException: OpenCL error [-1001]
            at org.lwjgl.demo.opencl.InfoUtil.checkCLError(InfoUtil.java:112)
            at org.lwjgl.demo.opencl.CLDemo.demo(CLDemo.java:33)
            at org.lwjgl.demo.opencl.CLDemo.main(CLDemo.java:27)

**Comment by Spasi** [comment]
Sounds like libffi/libffi#606. Please test the next snapshot (build 11) when it's available.

**Comment by adiantek** [comment]
Ok, when next snapshot will be available? I see that build 10 was released about 10 hours ago.

**Comment by adiantek** [comment]
I tested and it's okay now (CLDemo works too).
