### ISSUE TITLE
Error creating VmaAllocator

### ISSUE THREAD

**Issue by lwjglgamedev** [LWJGL/lwjgl3#638]
* LWJGL version: `3.3.0 snapshot` 
* LWJGL build : `11`
* Java version: `16`
* Platform: `Windows`
* Module: `vma`

### Description

I'm continuing the the tetsing of 3.3.0 snapshot and I've found a problem when invoking the `org.lwjgl.util.vma.Vma.vmaCreateAllocator` method. I get the following exception

```
java.lang.NullPointerException
	at org.lwjgl.system.Checks.check(Checks.java:188)
	at org.lwjgl.util.vma.VmaAllocatorCreateInfo.validate(VmaAllocatorCreateInfo.java:399)
	at org.lwjgl.util.vma.Vma.vmaCreateAllocator(Vma.java:1916)
	at org.vulkanb.TestVma.createVmaAllocator(TestVma.java:106)
	at org.vulkanb.TestVma.main(TestVma.java:117)
```

You can find below a simple class that triggers the error in my environment. The same code works ok with 3.2.3 version.
```java
package org.vulkanb;

import org.lwjgl.PointerBuffer;
import org.lwjgl.system.MemoryStack;
import org.lwjgl.util.vma.*;
import org.lwjgl.vulkan.*;

import java.nio.*;

import static org.lwjgl.util.vma.Vma.vmaCreateAllocator;
import static org.lwjgl.vulkan.VK11.*;

public class TestVma {

    private static final VkDevice createDevice(VkPhysicalDevice vkPhysicalDevice) {
        try (MemoryStack stack = MemoryStack.stackPush()) {
            // Define required extensions
            PointerBuffer requiredExtensions = stack.mallocPointer(1);
            requiredExtensions.put(0, stack.ASCII(KHRSwapchain.VK_KHR_SWAPCHAIN_EXTENSION_NAME));

            VkPhysicalDeviceFeatures vkPhysicalDeviceFeatures = VkPhysicalDeviceFeatures.calloc();
            vkGetPhysicalDeviceFeatures(vkPhysicalDevice, vkPhysicalDeviceFeatures);

            IntBuffer intBuffer = stack.mallocInt(1);
            VkQueueFamilyProperties.Buffer queuePropsBuff = VkQueueFamilyProperties.calloc(intBuffer.get(0));
            vkGetPhysicalDeviceQueueFamilyProperties(vkPhysicalDevice, intBuffer, queuePropsBuff);

            // Enable all the queue families
            int numQueuesFamilies = queuePropsBuff.capacity();
            VkDeviceQueueCreateInfo.Buffer queueCreationInfoBuf = VkDeviceQueueCreateInfo.callocStack(numQueuesFamilies, stack);
            for (int i = 0; i < numQueuesFamilies; i++) {
                FloatBuffer priorities = stack.callocFloat(queuePropsBuff.get(i).queueCount());
                queueCreationInfoBuf.get(i)
                        .sType(VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO)
                        .queueFamilyIndex(i)
                        .pQueuePriorities(priorities);
            }

            VkDeviceCreateInfo deviceCreateInfo = VkDeviceCreateInfo.callocStack(stack)
                    .sType(VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO)
                    .ppEnabledExtensionNames(requiredExtensions)
                    .pEnabledFeatures(vkPhysicalDeviceFeatures)
                    .pQueueCreateInfos(queueCreationInfoBuf);

            PointerBuffer pp = stack.mallocPointer(1);
            vkCheck(vkCreateDevice(vkPhysicalDevice, deviceCreateInfo, null, pp),
                    "Failed to create device");
            return new VkDevice(pp.get(0), vkPhysicalDevice, deviceCreateInfo);
        }
    }

    private static VkInstance createInstance() {
        try (MemoryStack stack = MemoryStack.stackPush()) {
            ByteBuffer appShortName = stack.UTF8("App");
            VkApplicationInfo appInfo = VkApplicationInfo.callocStack(stack)
                    .sType(VK_STRUCTURE_TYPE_APPLICATION_INFO)
                    .pApplicationName(appShortName)
                    .applicationVersion(1)
                    .pEngineName(appShortName)
                    .engineVersion(0)
                    .apiVersion(VK_API_VERSION_1_1);

            VkInstanceCreateInfo instanceInfo = VkInstanceCreateInfo.callocStack(stack)
                    .sType(VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO)
                    .pApplicationInfo(appInfo);

            PointerBuffer pInstance = stack.mallocPointer(1);
            vkCheck(vkCreateInstance(instanceInfo, null, pInstance), "Error creating instance");
            return new VkInstance(pInstance.get(0), instanceInfo);
        }
    }

    private static VkPhysicalDevice createPhysicalDevice(VkInstance vkInstance) {
        try (MemoryStack stack = MemoryStack.stackPush()) {
            // Get number of physical devices
            IntBuffer intBuffer = stack.mallocInt(1);
            vkCheck(vkEnumeratePhysicalDevices(vkInstance, intBuffer, null),
                    "Failed to get number of physical devices");
            int numDevices = intBuffer.get(0);
            if (numDevices <= 0) {
                throw new RuntimeException("No physical devices detected");
            }

            // Populate physical devices list pointer
            PointerBuffer pPhysicalDevices = stack.mallocPointer(numDevices);
            vkCheck(vkEnumeratePhysicalDevices(vkInstance, intBuffer, pPhysicalDevices),
                    "Failed to get physical devices");
            return new VkPhysicalDevice(pPhysicalDevices.get(0), vkInstance);
        }
    }

    private static void createVmaAllocator(VkInstance vkInstance, VkPhysicalDevice vkPhysicalDevice,
                                           VkDevice vkDevice) {
        try (MemoryStack stack = MemoryStack.stackPush()) {
            PointerBuffer pAllocator = stack.mallocPointer(1);

            VmaVulkanFunctions vmaVulkanFunctions = VmaVulkanFunctions.callocStack(stack)
                    .set(vkInstance, vkDevice);

            VmaAllocatorCreateInfo createInfo = VmaAllocatorCreateInfo.callocStack(stack)
                    .device(vkDevice)
                    .physicalDevice(vkPhysicalDevice)
                    .pVulkanFunctions(vmaVulkanFunctions);
            vkCheck(vmaCreateAllocator(createInfo, pAllocator),
                    "Failed to create VMA allocator");
        }
    }

    public static void main(String[] args) {
        try {
            try (MemoryStack stack = MemoryStack.stackPush()) {
                VkInstance vkInstance = createInstance();
                VkPhysicalDevice vkPhysicalDevice = createPhysicalDevice(vkInstance);
                VkDevice vkDevice = createDevice(vkPhysicalDevice);
                createVmaAllocator(vkInstance, vkPhysicalDevice, vkDevice);
            }
        } catch (Exception excp) {
            excp.printStackTrace();
        }
    }

    private static void vkCheck(int err, String errMsg) {
        if (err != VK_SUCCESS) {
            throw new RuntimeException(errMsg + ": " + err);
        }
    }
}
```

**Comment by httpdigest** [comment]
You need to provide the VkInstance through the `.instance()` member in `VmaAllocatorCreateInfo` as well. VMA made a change somewhere between the last 3.2.3 release and this 3.3.0 snapshot.

**Comment by lwjglgamedev** [comment]
Thanks! I was not aware of it.
