### ISSUE TITLE
Error CL_INVALID_GL_SHAREGROUP_REFERENCE_KHR in CLGLInteropDemo

### ISSUE THREAD

**Issue by devent** [LWJGL/lwjgl3#680]
### Version

3.3.0 (nightly), 3.2.3

### Platform

Linux x64

### JDK

OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

### Module

LWJGL samples, opencl

### Bug description

Try and run the CLGLInteropDemo.
Expected to see the Mandelbrot.
Actually the app terminates with the error:
```
java.lang.RuntimeException: java.lang.RuntimeException: OpenCL error [-1000]
	at com.anrisoftware.anlopencl.jme.opencl.Mandelbrot.<init>(Mandelbrot.java:462)
	at com.anrisoftware.anlopencl.jme.opencl.CLGLInteropDemo$1.run(CLGLInteropDemo.java:217)
Caused by: java.lang.RuntimeException: OpenCL error [-1000]
	at com.anrisoftware.anlopencl.jme.opencl.InfoUtil.checkCLError(InfoUtil.java:114)
	at com.anrisoftware.anlopencl.jme.opencl.InfoUtil.checkCLError(InfoUtil.java:109)
	at com.anrisoftware.anlopencl.jme.opencl.Mandelbrot.<init>(Mandelbrot.java:336)
	... 1 more
GAME ON!
GAME OVER!
```

Also try to run OpenCL with JME3 that is using Lwjgl 3.2.3.

```
Sep 27, 2021 4:41:22 PM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.4.0-stable
* Branch: HEAD
* Git Hash: cb5173b
* Build Date: 2021-05-30
Sep 27, 2021 4:41:22 PM com.jme3.system.lwjgl.LwjglContext initOpenCL
INFO: Initialize OpenCL with LWJGL3
Sep 27, 2021 4:41:22 PM com.jme3.system.lwjgl.LwjglContext initOpenCL
INFO: Available OpenCL platforms:
* Platform 1
*   Name: NVIDIA CUDA
*   Vendor: NVIDIA Corporation
*   Version: OpenCL 3.0 CUDA 11.4.136
*   Profile: FULL_PROFILE
*   Supports interop: true
*   Available devices:
*    * Device 1
*    *   Name: NVIDIA GeForce GTX 1050
*    *   Vendor: NVIDIA Corporation
*    *   Version: OpenCL 3.0 CUDA
*    *   Profile: FULL_PROFILE
*    *   Compiler version: OpenCL C 1.2 
*    *   Device type: DEFAULT
*    *   Compute units: 5
*    *   Work group size: 1024
*    *   Global memory: 2099904512B
*    *   Local memory: 49152B
*    *   Constant memory: 65536B
*    *   Supports double: true
*    *   Supports half floats: false
*    *   Supports writable 3d images: true
*    *   Supports interop: true
Sep 27, 2021 4:41:22 PM com.jme3.system.lwjgl.LwjglContext initOpenCL
INFO: chosen platform: NVIDIA CUDA
Sep 27, 2021 4:41:22 PM com.jme3.system.lwjgl.LwjglContext initOpenCL
INFO: chosen devices: [NVIDIA GeForce GTX 1050]
Sep 27, 2021 4:46:49 PM com.jme3.system.lwjgl.LwjglContext initOpenCL
SEVERE: Unable to create OpenCL context
com.jme3.opencl.OpenCLException: OpenCL error in clCreateContext: CL_INVALID_GL_CONTEXT_APPLE|CL_INVALID_GL_SHAREGROUP_REFERENCE_KHR (0xfffffc18)
```

clinfo

```
Number of platforms                               1
Platform Name                                   NVIDIA CUDA
Platform Vendor                                 NVIDIA Corporation
Platform Version                                OpenCL 3.0 CUDA 11.4.136
Platform Profile                                FULL_PROFILE
Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid cl_khr_pci_bus_info
Platform Host timer resolution                  0ns
Platform Extensions function suffix             NV

Platform Name                                   NVIDIA CUDA
Number of devices                                 1
Device Name                                     NVIDIA GeForce GTX 1050
Device Vendor                                   NVIDIA Corporation
Device Vendor ID                                0x10de
Device Version                                  OpenCL 3.0 CUDA
Driver Version                                  470.74
Device OpenCL C Version                         OpenCL C 1.2 
Device Type                                     GPU
Device Topology (NV)                            PCI-E, 01:00.0
Device Profile                                  FULL_PROFILE
Device Available                                Yes
Compiler Available                              Yes
Linker Available                                Yes
Max compute units                               5
Max clock frequency                             1493MHz
Compute Capability (NV)                         6.1
Device Partition                                (core)
    Max number of sub-devices                     1
    Supported partition types                     None
    Supported affinity domains                    (n/a)
Max work item dimensions                        3
Max work item sizes                             1024x1024x64
Max work group size                             1024
Preferred work group size multiple              32
Warp size (NV)                                  32
Max sub-groups per work group                   0
Preferred / native vector sizes                 
    char                                                 1 / 1       
    short                                                1 / 1       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 0 / 0        (n/a)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
Half-precision Floating-point support           (n/a)
Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
Address bits                                    64, Little-Endian
Global memory size                              2099904512 (1.956GiB)
Error Correction support                        No
Max memory allocation                           524976128 (500.7MiB)
Unified memory for Host and Device              No
Integrated memory (NV)                          No
Shared Virtual Memory (SVM) capabilities        (core)
    Coarse-grained buffer sharing                 Yes
    Fine-grained buffer sharing                   No
    Fine-grained system sharing                   No
    Atomics                                       No
Minimum alignment for any data type             128 bytes
Alignment of base address                       4096 bits (512 bytes)
Preferred alignment for atomics                 
    SVM                                           0 bytes
    Global                                        0 bytes
    Local                                         0 bytes
Max size for global variable                    0
Preferred total size of global vars             0
Global Memory cache type                        Read/Write
Global Memory cache size                        245760 (240KiB)
Global Memory cache line size                   128 bytes
Image support                                   Yes
    Max number of samplers per kernel             32
    Max size for 1D images from buffer            268435456 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             16384x32768 pixels
    Max 3D image size                             16384x16384x16384 pixels
    Max number of read image args                 256
    Max number of write image args                16
    Max number of read/write image args           0
Max number of pipe args                         0
Max active pipe reservations                    0
Max pipe packet size                            0
Local memory type                               Local
Local memory size                               49152 (48KiB)
Registers per block (NV)                        65536
Max number of constant args                     9
Max constant buffer size                        65536 (64KiB)
Max size of kernel argument                     4352 (4.25KiB)
Queue properties (on host)                      
    Out-of-order execution                        Yes
    Profiling                                     Yes
Queue properties (on device)                    
    Out-of-order execution                        No
    Profiling                                     No
    Preferred size                                0
    Max size                                      0
Max queues on device                            0
Max events on device                            0
Prefer user sync for interop                    No
Profiling timer resolution                      1000ns
Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Sub-group independent forward progress        No
    Kernel execution timeout (NV)                 Yes
Concurrent copy and kernel execution (NV)       Yes
    Number of async copy engines                  2
    IL version                                    (n/a)
printf() buffer size                            1048576 (1024KiB)
Built-in kernels                                (n/a)
Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid cl_khr_pci_bus_info

NULL platform behavior
clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  NVIDIA CUDA
clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [NV]
clCreateContext(NULL, ...) [default]            Success [NV]
clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No platform
clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  Invalid device type for platform
clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform

ICD loader properties
ICD loader Name                                 OpenCL ICD Loader
ICD loader Vendor                               OCL Icd free software
ICD loader Version                              2.2.11
ICD loader Profile                              OpenCL 2.1
        NOTE:   your OpenCL library only supports OpenCL 2.1,
                but some installed platforms support OpenCL 3.0.
                Programs using 3.0 features may crash
                or behave unexpectedly

    created
    18h
    last reply
    10h
    2
    replies
    28
    views
    2
    users
    1
    link
```

**Comment by Spasi** [comment]
Hey @devent, I cannot reproduce this.

Your ICD loader looks old (`2.2.11` was released Jan 2017), so my guess is a reinstallation will fix it. Try something like:

```
sudo apt remove ocl-icd-libopencl1
sudo apt install ocl-icd-opencl-dev clinfo
```

**Comment by devent** [comment]
Don't know if this is a good idea? I will lose my whole desktop.

```
The following packages will be REMOVED:
  celluloid clinfo dolphin ffmpegthumbnailer ffmpegthumbs gimp gstreamer1.0-libav gstreamer1.0-plugins-bad gwenview hypnotix kde-baseapps kde-plasma-desktop khelpcenter kinfocenter kio-extras konqueror konsole
  ksysguard libavcodec-dev libavcodec-extra libavcodec-extra58 libavdevice58 libavfilter7 libavformat-dev libavformat58 libavresample-dev libavresample4 libavutil-dev libavutil56 libcaf-openmpi-3
  libchromaprint1 libcoarrays-openmpi-dev libfaudio0 libffmpegthumbnailer4v5 libgegl-0.4-0 libgimp2.0 libhdf5-openmpi-103 libhwloc-plugins libkf5baloowidgets-bin libkf5baloowidgets5 libkf5filemetadata-bin
  libkf5khtml-bin libkf5khtml5 libkf5notifyconfig5 libmpv1 libopencv-calib3d-dev libopencv-calib3d4.2 libopencv-contrib-dev libopencv-contrib4.2 libopencv-dev libopencv-features2d-dev libopencv-features2d4.2
  libopencv-highgui-dev libopencv-highgui4.2 libopencv-objdetect-dev libopencv-objdetect4.2 libopencv-shape-dev libopencv-shape4.2 libopencv-stitching-dev libopencv-stitching4.2 libopencv-superres-dev
  libopencv-superres4.2 libopencv-video-dev libopencv-video4.2 libopencv-videoio-dev libopencv-videoio4.2 libopencv-videostab-dev libopencv-videostab4.2 libopencv-viz-dev libopencv-viz4.2 libopencv4.2-java
  libopencv4.2-jni libopenmpi-dev libopenmpi3 libpmix2 libpostproc55 libprocessui7 libqt5webenginecore5 libqt5webenginewidgets5 libswresample-dev libswresample3 libswscale-dev libswscale5 libvtk6.3 libwine
  mint-meta-codecs ocl-icd-libopencl1 ocl-icd-opencl-dev openmpi-bin phonon4qt5 phonon4qt5-backend-vlc plasma-desktop plasma-workspace powerdevil vlc vlc-plugin-base vlc-plugin-video-output wine wine-stable
  wine64 yakuake
```

**Comment by devent** [comment]
I forget to tell that I was running in Nvidia OnDemand mode. The JME3 people suggested that it could be that the OpenGL context was created on Intel and the OpenCL context was created on Nvidia. I tried to run it in Nvidia mode and now the demo works.

I just have the problem that my graphic cards tends to overheat in Nvidia mode. Also I don’t want to run always in Nvidia mode because of the power consumption.

Is there a way to tell Lwjgl to use Nvidia for OpenGL?

**Comment by Spasi** [comment]
Try launching your application with:

```
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia java <params>
```

([source](https://askubuntu.com/a/1201550))

**Comment by devent** [comment]
Thank you. I got some info from Arch Linux https://wiki.archlinux.org/title/PRIME
The prime-run script works fine. I have now Eclipse run in Nvidia mode.
https://gist.github.com/abenson/a5264836c4e6bf22c8c8415bb616204a
