### ISSUE TITLE
Unable to update the GLFW gamepad mappings from https://github.com/gabomdq/SDL_GameControllerDB

### ISSUE THREAD

**Issue by Pesegato** [LWJGL/lwjgl3#689]
### Version

3.2.3

### Platform

Windows x64

### JDK

Oracle Java 1.8_77

### Module

GLFW

### Bug description

This code

```
            RandomAccessFile aFile = new RandomAccessFile("assets/gamecontrollerdb.txt","r");

            FileChannel inChannel = aFile.getChannel();
            long fileSize = inChannel.size();

            ByteBuffer buffer = ByteBuffer.allocate((int) fileSize);
            inChannel.read(buffer);
            buffer.flip();

            GLFW.glfwUpdateGamepadMappings(buffer);
```

### Stacktrace or crash log output

```shell
java.lang.IllegalArgumentException: Missing termination
	at org.lwjgl.system.Checks.assertNT(Checks.java:108) ~[lwjgl-3.2.3.jar:build 13]
	at org.lwjgl.system.Checks.checkNT1(Checks.java:139) ~[lwjgl-3.2.3.jar:build 13]
	at org.lwjgl.glfw.GLFW.glfwUpdateGamepadMappings(GLFW.java:4258) ~[lwjgl-glfw-3.2.3.jar:build 13]
```

**Comment by Pesegato** [comment]
This code

            RandomAccessFile aFile = new RandomAccessFile("assets/gamecontrollerdb.txt","r");

            FileChannel inChannel = aFile.getChannel();
            long fileSize = inChannel.size();

            ByteBuffer buffer = ByteBuffer.allocateDirect((int) fileSize + 1);
            inChannel.read(buffer);
            buffer.rewind();

            if (!GLFW.glfwUpdateGamepadMappings(buffer)) {
                log.error("CRITICAL: Error while loading SDL Gamepad mappings!");
                System.out.println("CRITICAL: Error while loading SDL Gamepad mappings!");
                System.exit(0);
            }

Will show the critical warning and exit, regardless of what I write on gamecontroller.txt. From the debugger, I can see the buffer filled with the file's data, so it's not a loading issue..,

**Comment by httpdigest** [comment]
Cannot reproduce.
You _do_ call `GLFW.glfwInit();` before that, right?

**Comment by Pesegato** [comment]
That was it, I was calling the code too early. Thanks!
