### ISSUE TITLE
java.lang.NoClassDefFoundError: org/lwjgl/Version

### ISSUE THREAD

**Issue by a2py** [LWJGL/lwjgl3#760]
### Question

hi every game i want to made in eclipse this error show up 
java.lang.NoClassDefFoundError: org/lwjgl/.......
for example trying a version printer:
the code:
###########################################
import org.lwjgl.Version;

public class MainApp {
		public static void main(String[] args) {
			System.out.println(Version.getVersion());
	}
}
###########################################
Error:
###########################################
Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/Version
	at main.MainApp.main(MainApp.java:5)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.Version
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 1 more
###########################################

**Comment by a2py** [comment]
also packages are installed

**Comment by httpdigest** [comment]
Did you add the LWJGL 3 jars to the modulepath or to the classpath? This is a typical problem starting with Java 9, where - in besides the classpath you now have the modulepath. And Eclipse will (when you answer with "yes" in the new project wizzard about whether it should create a module file) create a module-info.java file. In this case, your application is a module and you must also declare the dependencies in your module-info.java file.

**Comment by a2py** [comment]
ok thank u
