### ISSUE TITLE
`glfwInit` hangs after setting `glfw_async`

### ISSUE THREAD

**Issue by pderoovere** [LWJGL/lwjgl3#767]
## Version
3.3.1

## Platform
macOS arm64
macOS x86-64

## JDK
BellSoft Liberica Full JDK 8u332+9 ARM 64 bit for macOS

## Description
We're using LWJGL together with JavaFX. After setting `Configuration.GLFW_LIBRARY_NAME.set("glfw_async")`, calling `GLFW.glfwInit()` hangs. 
A thread dump seems to indicate the native method is being called.
```
java.lang.Thread.State: RUNNABLE
	at org.lwjgl.system.JNI.invokeI(Native Method)
	at org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:1047)
```
I'm guessing this is related to #754, as discussed [here](https://hub.jmonkeyengine.org/t/macos-support-overhaul-apple-m1-and-breaking-changes/45258/134). What would be the best way to deal with this?

**Comment by Spasi** [comment]
Hey @pderoovere,

Could you please try again with the latest LWJGL snapshot? Also, make sure `-XstartOnFirstThread` is **not** used and that JavaFX is initialized first, before touching anything in GLFW.

**Comment by pderoovere** [comment]
Hi @Spasi,

Unfortunately the latest snapshot leads to the same behavior. 
After calling `GLFW.glfwInit()`, the following (debug) statements are logged before it hangs:

```
Version: 3.3.2-snapshot+3
OS: Mac OS X v12.6
JRE: macOS aarch64 1.8.0_332
JVM: OpenJDK 64-Bit Server VM v25.332-b09 by BellSoft
Loading JNI library: lwjgl
Module: org.lwjgl
Loaded from org.lwjgl.librarypath: <EDITED>/3.3.2-snapshot+3/arm64/liblwjgl.dylib
Loading library: glfw_async
Module: org.lwjgl.glfw
Loaded from org.lwjgl.librarypath: <EDITED>/3.3.2-snapshot+3/arm64/libglfw_async.dylib
```

**Comment by Spasi** [comment]
Hey @pderoovere,

If possible, could you please test the following scenarios?

- Running the application on x64 instead of ARM (either on a native x64 Mac or via Rosetta).
- Running `glfwInit` without any JavaFX interaction, with `-XstartOnFirstThread`, without `glfw_async`.
- Running `glfwInit` without any JavaFX interaction, without `-XstartOnFirstThread`, with `glfw_async`.

Finally, could you prepare a simple code sample that reproduces the issue? It should be as close as possible to the way JavaFX and GLFW are used together in your real application.

**Comment by Spasi** [comment]
Any updates on this?

**Comment by andete** [comment]
[minimal.zip](https://github.com/LWJGL/lwjgl3/files/11030830/minimal.zip)

Hello, here you can find a minimal maven build program that has the same javafx and threading behaviour as the real thing, and exhibits the same hanging behaviour as well.

**Comment by Spasi** [comment]
@andete I tried to run the example on macOS but couldn't get it working. Could you please extend pom.xml with run functionality (e.g. `exec-maven-plugin` or `javafx-maven-plugin`) and possibly add a .sh script with the appropriate command to run? Also, what JavaFX version are you using? Is JavaFX embedded in the JDK (which version?) or using OpenJFX artifacts?

I did have more success on Windows though. I tried it there first to set an expectation of what I'm supposed to be seeing. There wasn't much, just a spinner component in the middle. Is there supposed to be more? What are you rendering with OpenGL?

In any case, it would be nice if you could also simplify it more, there's too much code in the example to investigate and understand. A simple GL component that clears the background to a fixed color should be enough.

**Comment by andete** [comment]
[minimal.zip](https://github.com/LWJGL/lwjgl3/files/12514433/minimal.zip)

Hello, please find attached a further simplified example, also with run sh scripts.
This program just clears the background to a fixed color.

JDK is a JDK with build-in javaFX:

[LWJGL] 	 OS: Mac OS X v13.5.1
[LWJGL] 	JRE: macOS aarch64 1.8.0_362
[LWJGL] 	JVM: OpenJDK 64-Bit Server VM v25.362-b09 by Azul Systems, Inc.

openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Zulu 8.68.0.21-CA-macos-aarch64) (build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Zulu 8.68.0.21-CA-macos-aarch64) (build 25.362-b09, mixed mode)
