### ISSUE TITLE
Assimp dll won't load

### ISSUE THREAD

**Issue by IkeOTL** [LWJGL/lwjgl3#792]
### Version

3.3.2 (nightly)

### Platform

Windows x64

### JDK

java version "17.0.2" 2022-01-18 LTS

### Module

LWJGL assimp

### Bug description

When trying to load a scene loading the native dll is failing.

`java.lang.UnsatisfiedLinkError: Failed to load library: C:\Users\KudoD\AppData\Local\Temp\lwjglKudoD\3.3.2-build-2\assimp.dll (error code = 126)`

This is happening when the program hits `aiImportFileEx` both in my project and the `WavefrontObjDemo` demo

### Stacktrace or crash log output

```shell
java.lang.UnsatisfiedLinkError: Failed to load library: C:\Users\KudoD\AppData\Local\Temp\lwjglKudoD\3.3.2-build-2\assimp.dll (error code = 126)
	at org.lwjgl.system.windows.WindowsLibrary.loadLibrary(WindowsLibrary.java:46)
	at org.lwjgl.system.windows.WindowsLibrary.<init>(WindowsLibrary.java:33)
	at org.lwjgl.system.APIUtil.apiCreateLibrary(APIUtil.java:109)
	at org.lwjgl.system.Library.loadNative(Library.java:367)
	at org.lwjgl.system.Library.loadNativeFromLibraryPath(Library.java:356)
	at org.lwjgl.system.Library.loadNative(Library.java:270)
	at org.lwjgl.system.Library.loadNative(Library.java:228)
	at org.lwjgl.assimp.Assimp.<clinit>(Assimp.java:168)
	at org.lwjgl.demo.opengl.assimp.WavefrontObjDemo.loadModel(WavefrontObjDemo.java:203)
	at org.lwjgl.demo.opengl.assimp.WavefrontObjDemo.init(WavefrontObjDemo.java:159)
	at org.lwjgl.demo.opengl.assimp.WavefrontObjDemo.run(WavefrontObjDemo.java:318)
	at org.lwjgl.demo.opengl.assimp.WavefrontObjDemo.main(WavefrontObjDemo.java:334)
```

**Comment by Spasi** [comment]
Hey @IkeOTL,

It's a known issue. See #781, I will post there when it's fixed.
