### ISSUE TITLE
Cannot load native libraries on 3.3.2 build 2

### ISSUE THREAD

**Issue by tlf30** [LWJGL/lwjgl3#798]
### Version

3.3.2 (nightly)

### Platform

Windows x64

### JDK

OpenJDK 64-Bit Server VM v18+36 by Eclipse Adoptium

### Module

Assimp, others

### Bug description

Updated to 3.3.2 build 2 and cannot load native libraries anymore. 
I was on build 1 and it was working fine.

See gist: https://gist.github.com/tlf30/056f9da79f7f2041d6fb4b8632455c73
(Ignore the assertion errors in the gist, I'm not sure why those happen, but they happen on 3.3.1 as well, which works just fine)

```
[LWJGL] Version: 3.3.2 build 2
[LWJGL] 	 OS: Windows 10 v10.0
[LWJGL] 	JRE: Windows amd64 18
[LWJGL] 	JVM: OpenJDK 64-Bit Server VM v18+36 by Eclipse Adoptium
[LWJGL] Loading JNI library: lwjgl
[LWJGL] 	Module: org.lwjgl
[LWJGL] 	Using SharedLibraryLoader...
[LWJGL] 	Found at: C:\Users\Trevor\AppData\Local\Temp\lwjglTrevor\3.3.2-build-2\lwjgl.dll
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Users\Trevor\AppData\Local\Temp\lwjglTrevor\3.3.2-build-2\lwjgl.dll
[LWJGL] Warning: Failed to instantiate memory allocator: org.lwjgl.system.jemalloc.JEmallocAllocator. Using the system default.
[LWJGL] Java 9 check intrinsics enabled
[LWJGL] Java 9 stack walker enabled
[LWJGL] Closure Registry: simple
[LWJGL] MemoryUtil allocator: DebugAllocator
```

```
[2022-08-18 11:38:41] [SEVERE ] Uncaught exception 
java.lang.UnsatisfiedLinkError: Failed to load library: C:\Users\Trevor\AppData\Local\Temp\lwjglTrevor\3.3.2-build-2\assimp.dll (error code = 126)
	at org.lwjgl.system.windows.WindowsLibrary.loadLibrary(WindowsLibrary.java:46)
	at org.lwjgl.system.windows.WindowsLibrary.<init>(WindowsLibrary.java:33)
	at org.lwjgl.system.APIUtil.apiCreateLibrary(APIUtil.java:109)
	at org.lwjgl.system.Library.loadNative(Library.java:367)
	at org.lwjgl.system.Library.loadNativeFromLibraryPath(Library.java:356)
	at org.lwjgl.system.Library.loadNative(Library.java:270)
	at org.lwjgl.system.Library.loadNative(Library.java:228)
	at org.lwjgl.assimp.Assimp.<clinit>(Assimp.java:168)
	at org.lwjglx.debug.$Proxy$1613.aiGetVersionMajor27(Unknown Source)
	at io.tlf.outside.lib.assets.loader.AssimpAssetLoader.load(AssimpAssetLoader.java:589)
	at io.tlf.outside.core.components.registry.GlobalEngineComponentRegistry.load(GlobalEngineComponentRegistry.java:65)
	at io.tlf.outside.client.Client.buildClient(Client.java:260)
	at io.tlf.outside.client.Client$1.run(Client.java:92)
```

**Comment by Spasi** [comment]
Hey @tlf30,

See  #781.

**Comment by tlf30** [comment]
Ah, thank you @Spasi. My github searching skills failed me. 
Will there be another snapshot out soon that will include this fix?

**Comment by Spasi** [comment]
Yes, I'll post again in 781 when it's available.
