### ISSUE TITLE
Searching in linux/x64, yet JVM looks in amd64

### ISSUE THREAD

**Issue by Khhs167** [LWJGL/lwjgl3#826]
### Version

3.3.1

### Platform

Linux x64

### JDK

OpenJDK 17, straight from AUR

### Module

JWJGL Core

### Bug description

This is a simple issue: LWJGL binaries are in `linux/x86` but JVM wants to look in AMD64. I have no idea why it is like this, but it happened all of a sudden, most likely due to a linux update.

### Stacktrace or crash log output

```shell
[LWJGL] Platform/architecture mismatch detected for module: org.lwjgl
	JVM platform:
		Linux amd64 17.0.5
		OpenJDK 64-Bit Server VM v17.0.5+1 by Oracle Corporation
	Platform available on classpath:
		linux/x64
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.so
	at org.lwjgl.system.Library.loadSystem(Library.java:164)
	at org.lwjgl.system.Library.loadSystem(Library.java:63)
	at org.lwjgl.system.Library.<clinit>(Library.java:51)
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:30)
	at net.minecraftnt.client.platform.Window.<init>(Window.java:35)
	at net.minecraftnt.client.platform.Window.<init>(Window.java:27)
	at net.minecraftnt.client.Client.<init>(Client.java:21)
	at net.minecraftnt.client.Client.main(Client.java:76)
```

**Comment by Khhs167** [comment]
Huh, updated to LWJGL 3.2.2-SNAPSHOT and it worked. No idea why tho...
