### ISSUE TITLE
"Invalid value for parameter" error in the latest snapshot build

### ISSUE THREAD

**Issue by Ali-RS** [LWJGL/lwjgl3#837]
### Version

3.3.2 (nightly)

### Platform

Linux x64

### JDK

Adoptium OpenJDK 19

### Module

LWJGL Core, GLFW

### Bug description

Hi,

After upgrading to LWJGL `3.3.2-snapshot+8` I am getting this error when running my project. I am using jMonkeyEngine. 

It works fine in the LWJGL `3.3.2-snapshot+7` and older versions.  

### Stacktrace or crash log output

```shell
18:02:50,890 ERROR [LegacyApplication] Invalid value for parameter
java.lang.Exception: Invalid value for parameter
	at com.jme3.system.lwjgl.LwjglWindow$1.invoke(LwjglWindow.java:229) [jme3-lwjgl3-3.6.0-SNAPSHOT.jar:3.6.0-SNAPSHOT]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) [lwjgl-glfw-3.3.2-SNAPSHOT.jar:build 8]
	at org.lwjgl.system.JNI.invokeI(Native Method) ~[lwjgl-3.3.2-SNAPSHOT.jar:build 8]
	at org.lwjgl.glfw.GLFW.glfwInit(GLFW.java:1071) [lwjgl-glfw-3.3.2-SNAPSHOT.jar:build 8]
	at com.jme3.system.lwjgl.LwjglWindow.createContext(LwjglWindow.java:233) [jme3-lwjgl3-3.6.0-SNAPSHOT.jar:3.6.0-SNAPSHOT]
	at com.jme3.system.lwjgl.LwjglWindow.initInThread(LwjglWindow.java:582) [jme3-lwjgl3-3.6.0-SNAPSHOT.jar:3.6.0-SNAPSHOT]
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:704) [jme3-lwjgl3-3.6.0-SNAPSHOT.jar:3.6.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
18:02:52,590 INFO  [LwjglContext] LWJGL 3.3.2-snapshot+8 context running on thread jME3 Main
 * Graphics Adapter: GLFW 3.4.0 Wayland X11 GLX Null EGL OSMesa monotonic shared
18:02:53,022 INFO  [GLRenderer] OpenGL Renderer Information
 * Vendor: X.Org
 * Renderer: AMD CEDAR (DRM 2.50.0 / 5.4.0-58-generic, LLVM 10.0.0)
 * OpenGL Version: 3.3 (Core Profile) Mesa 20.0.8
 * GLSL Version: 3.30
 * Profile: Core
```
```

**Comment by Spasi** [comment]
Hey @Ali-RS,

This error is reporting a bad controller mapping entry. It is harmless, the entry is simply skipped and you can safely ignore the error.

This is supposed to never happen in GLFW, it was my mistake when I updated to the latest SDL_GameControllerDB version. It will go away in the next snapshot. If it can't wait, [this](https://build.lwjgl.org/nightly/linux/x64/libglfw.so) fresh GLFW build is fixed.

**Comment by Ali-RS** [comment]
Ok, thanks

**Comment by Spasi** [comment]
Hey @Ali-RS,

LWJGL `3.3.2-snapshot+9` is now available and this error should be gone. Also updated to latest SDL_GameControllerDB.

**Comment by Ali-RS** [comment]
Great, thank you so much @Spasi
