### ISSUE TITLE
Failed to locate library: libEGL.dll

### ISSUE THREAD

**Issue by Zegute** [LWJGL/lwjgl3#914]
### Version

3.3.2

### Platform

Windows x64

### JDK

JustJ OpenJDK 17.0.7

### Module

EGL

### Bug description

When I downlaod custom package, it don't have egl native jars. When I run the code, the native library is not found

### Stacktrace or crash log output

```shell
[LWJGL] Version: 3.3.0 build 21
[LWJGL] 	 OS: Windows Server 2022 v10.0
[LWJGL] 	JRE: Windows amd64 17.0.7
[LWJGL] 	JVM: OpenJDK 64-Bit Server VM v17.0.7+7 by Eclipse Adoptium
[LWJGL] Loading JNI library: lwjgl
[LWJGL] 	Module: org.lwjgl
[LWJGL] 	Using SharedLibraryLoader...
[LWJGL] 	Found at: C:\Users\ADMINI~1\AppData\Local\Temp\lwjglAdministrator\3.3.0-build-21\lwjgl.dll
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Users\ADMINI~1\AppData\Local\Temp\lwjglAdministrator\3.3.0-build-21\lwjgl.dll
[LWJGL] Loading library: libEGL
[LWJGL] 	Module: org.lwjgl.egl
[LWJGL] 	libEGL.dll not found in org.lwjgl.librarypath=C:\Users\ADMINI~1\AppData\Local\Temp\lwjglAdministrator\3.3.0-build-21
[LWJGL] 	libEGL.dll not found in system paths
[LWJGL] 	libEGL.dll not found in java.library.path=D:\eclipse\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.7.v20230425-1502\jre\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;D:/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.7.v20230425-1502/jre/bin/server;D:/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.7.v20230425-1502/jre/bin;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files (x86)\Cuminas\Document Express DjVu Plug-in\;D:\graalvm-jdk-17.0.7+8.1\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Common Files\GTK\2.0\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Cloudflare\Cloudflare WARP\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;D:\TDM-GCC-64\bin;C:\Users\Administrator\AppData\Roaming\wix311-binaries;C:\Users\Administrator\AppData\Local\Programs\mongosh\;;D:\eclipse;;.
[LWJGL] Loading library: EGL
[LWJGL] 	Module: org.lwjgl.egl
[LWJGL] 	EGL.dll not found in org.lwjgl.librarypath=C:\Users\ADMINI~1\AppData\Local\Temp\lwjglAdministrator\3.3.0-build-21
[LWJGL] 	EGL.dll not found in system paths
[LWJGL] 	EGL.dll not found in java.library.path=D:\eclipse\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.7.v20230425-1502\jre\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;D:/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.7.v20230425-1502/jre/bin/server;D:/eclipse//plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.7.v20230425-1502/jre/bin;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files (x86)\Cuminas\Document Express DjVu Plug-in\;D:\graalvm-jdk-17.0.7+8.1\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Common Files\GTK\2.0\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Cloudflare\Cloudflare WARP\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;D:\TDM-GCC-64\bin;C:\Users\Administrator\AppData\Roaming\wix311-binaries;C:\Users\Administrator\AppData\Local\Programs\mongosh\;;D:\eclipse;;.
[LWJGL] Failed to load a library. Possible solutions:
	a) Install the library or the driver that provides the library.
	b) Ensure that the library is accessible from the system library paths.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: libEGL.dll
	at org.lwjgl.system.Library.loadNative(Library.java:327)
	at org.lwjgl.system.Library.loadNative(Library.java:414)
	at org.lwjgl.system.Library.loadNative(Library.java:381)
	at org.lwjgl.egl.EGL.create(EGL.java:65)
	at org.lwjgl.egl.EGL.<clinit>(EGL.java:48)
	at org.lwjgl.egl.EGL10.eglSwapBuffers(EGL10.java:462)
	at org.hikagame.phantom.DisplayGLESImpl.swapBuffers(DisplayGLESImpl.java:97)
	at org.hikagame.phantom.Display.swapBuffers(Display.java:7)
	at org.hikagame.phantom.Main.main(Main.java:7)
```

**Comment by Spasi** [comment]
LWJGL does not ship with an EGL implementation, you have to install one separately.
