### ISSUE TITLE
lwjgl.dll missing while running code from module openvr

### ISSUE THREAD

**Issue by AustXnsheep** [LWJGL/lwjgl3#971]
### Version

3.3.3

### Platform

Windows x64

### JDK

Corretto-17, "17.0.10"

### Module

lwjgl-openvr

### Bug description

Running any code from this library returns an error complaining about a missing .dll file. I can use the dll files from other modules E.X. new LwjglApplication(new Main(),  "Ripple", 800, 600);

But when I run code related to the openvr module 
E.X. VR_IsRuntimeInstalled()

First time making a issue report, sorry if it doesn't fit standards.

### Stacktrace or crash log output

```shell
[LWJGL] Platform/architecture mismatch detected for module: org.lwjgl
	JVM platform:		Windows amd64 17.0.10
		OpenJDK 64-Bit Server VM v17.0.10+7-LTS by Amazon.com Inc.
	Platform available on classpath:
		windows/x64
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:134)
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
	at org.lwjgl.system.Library.loadSystem(Library.java:174)
	at org.lwjgl.system.Library.loadSystem(Library.java:64)
	at org.lwjgl.system.Library.<clinit>(Library.java:52)
	at org.lwjgl.openvr.VR.<clinit>(VR.java:27)
	at git.austxnsheep.Main.create(Main.java:69)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:150)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
```

**Comment by AustXnsheep** [comment]
Resolved.
