### ISSUE TITLE
[LWJGL] GLFW_PLATFORM_ERROR error on Parallels for Mac

### ISSUE THREAD

**Issue by ByerN** [LWJGL/lwjgl3#989]
### Version

3.3.3

### Platform

macOS arm64

### JDK

openjdk version "17.0.2"

### Module

GLFW

### Bug description

LWJGL v3.3.3 is crashing on Parallels Mac. It looks like it is directly related to the bug in GLFW https://github.com/glfw/glfw/issues/2467 which seems to be fixed in the new version.

Are there plans to upgrade the GLFW lib version in LWJGL?

### Stacktrace or crash log output

```shell
[LWJGL] GLFW_PLATFORM_ERROR error
        Description : WGL: Failed to retrieve pixel format attributes: The operation completed successfully.
        Stacktrace  :
                org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2058)
                org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2229)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:527)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:463)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
                com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:163)
                com.byern.game.desktop.DemoDesktopLauncherScala$.main(DemoDesktopLauncherScala.scala:25)
                com.byern.game.desktop.DemoDesktopLauncherScala.main(DemoDesktopLauncherScala.scala)
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:530)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:463)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:449)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:163)
        at com.byern.game.desktop.DemoDesktopLauncherScala$.main(DemoDesktopLauncherScala.scala:25)
        at com.byern.game.desktop.DemoDesktopLauncherScala.main(DemoDesktopLauncherScala.scala)
```

**Comment by Spasi** [comment]
Hey @ByerN,

LWJGL 3.3.4 snapshots include the latest GLFW changes.

**Comment by ByerN** [comment]
Thanks, I confirm that the 3.3.4 snapshot passed my smoke tests - the issue is not occurring anymore.
